// Code generated by go-swagger; DO NOT EDIT.

package catalog_item_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// CatalogItemServiceGetCatalogItemReader is a Reader for the CatalogItemServiceGetCatalogItem structure.
type CatalogItemServiceGetCatalogItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CatalogItemServiceGetCatalogItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCatalogItemServiceGetCatalogItemOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCatalogItemServiceGetCatalogItemDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCatalogItemServiceGetCatalogItemOK creates a CatalogItemServiceGetCatalogItemOK with default headers values
func NewCatalogItemServiceGetCatalogItemOK() *CatalogItemServiceGetCatalogItemOK {
	return &CatalogItemServiceGetCatalogItemOK{}
}

/*
CatalogItemServiceGetCatalogItemOK describes a response with status code 200, with default header values.

A successful response.
*/
type CatalogItemServiceGetCatalogItemOK struct {
	Payload *models.V1GetCatalogItemResponse
}

// IsSuccess returns true when this catalog item service get catalog item o k response has a 2xx status code
func (o *CatalogItemServiceGetCatalogItemOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this catalog item service get catalog item o k response has a 3xx status code
func (o *CatalogItemServiceGetCatalogItemOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this catalog item service get catalog item o k response has a 4xx status code
func (o *CatalogItemServiceGetCatalogItemOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this catalog item service get catalog item o k response has a 5xx status code
func (o *CatalogItemServiceGetCatalogItemOK) IsServerError() bool {
	return false
}

// IsCode returns true when this catalog item service get catalog item o k response a status code equal to that given
func (o *CatalogItemServiceGetCatalogItemOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the catalog item service get catalog item o k response
func (o *CatalogItemServiceGetCatalogItemOK) Code() int {
	return 200
}

func (o *CatalogItemServiceGetCatalogItemOK) Error() string {
	return fmt.Sprintf("[POST /v1/catalogitem/get][%d] catalogItemServiceGetCatalogItemOK  %+v", 200, o.Payload)
}

func (o *CatalogItemServiceGetCatalogItemOK) String() string {
	return fmt.Sprintf("[POST /v1/catalogitem/get][%d] catalogItemServiceGetCatalogItemOK  %+v", 200, o.Payload)
}

func (o *CatalogItemServiceGetCatalogItemOK) GetPayload() *models.V1GetCatalogItemResponse {
	return o.Payload
}

func (o *CatalogItemServiceGetCatalogItemOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GetCatalogItemResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCatalogItemServiceGetCatalogItemDefault creates a CatalogItemServiceGetCatalogItemDefault with default headers values
func NewCatalogItemServiceGetCatalogItemDefault(code int) *CatalogItemServiceGetCatalogItemDefault {
	return &CatalogItemServiceGetCatalogItemDefault{
		_statusCode: code,
	}
}

/*
CatalogItemServiceGetCatalogItemDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CatalogItemServiceGetCatalogItemDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this catalog item service get catalog item default response has a 2xx status code
func (o *CatalogItemServiceGetCatalogItemDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this catalog item service get catalog item default response has a 3xx status code
func (o *CatalogItemServiceGetCatalogItemDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this catalog item service get catalog item default response has a 4xx status code
func (o *CatalogItemServiceGetCatalogItemDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this catalog item service get catalog item default response has a 5xx status code
func (o *CatalogItemServiceGetCatalogItemDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this catalog item service get catalog item default response a status code equal to that given
func (o *CatalogItemServiceGetCatalogItemDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the catalog item service get catalog item default response
func (o *CatalogItemServiceGetCatalogItemDefault) Code() int {
	return o._statusCode
}

func (o *CatalogItemServiceGetCatalogItemDefault) Error() string {
	return fmt.Sprintf("[POST /v1/catalogitem/get][%d] CatalogItemService_GetCatalogItem default  %+v", o._statusCode, o.Payload)
}

func (o *CatalogItemServiceGetCatalogItemDefault) String() string {
	return fmt.Sprintf("[POST /v1/catalogitem/get][%d] CatalogItemService_GetCatalogItem default  %+v", o._statusCode, o.Payload)
}

func (o *CatalogItemServiceGetCatalogItemDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *CatalogItemServiceGetCatalogItemDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
