// Code generated by go-swagger; DO NOT EDIT.

package catalog_item_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// NewCatalogItemServiceGetCatalogItemParams creates a new CatalogItemServiceGetCatalogItemParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCatalogItemServiceGetCatalogItemParams() *CatalogItemServiceGetCatalogItemParams {
	return &CatalogItemServiceGetCatalogItemParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCatalogItemServiceGetCatalogItemParamsWithTimeout creates a new CatalogItemServiceGetCatalogItemParams object
// with the ability to set a timeout on a request.
func NewCatalogItemServiceGetCatalogItemParamsWithTimeout(timeout time.Duration) *CatalogItemServiceGetCatalogItemParams {
	return &CatalogItemServiceGetCatalogItemParams{
		timeout: timeout,
	}
}

// NewCatalogItemServiceGetCatalogItemParamsWithContext creates a new CatalogItemServiceGetCatalogItemParams object
// with the ability to set a context for a request.
func NewCatalogItemServiceGetCatalogItemParamsWithContext(ctx context.Context) *CatalogItemServiceGetCatalogItemParams {
	return &CatalogItemServiceGetCatalogItemParams{
		Context: ctx,
	}
}

// NewCatalogItemServiceGetCatalogItemParamsWithHTTPClient creates a new CatalogItemServiceGetCatalogItemParams object
// with the ability to set a custom HTTPClient for a request.
func NewCatalogItemServiceGetCatalogItemParamsWithHTTPClient(client *http.Client) *CatalogItemServiceGetCatalogItemParams {
	return &CatalogItemServiceGetCatalogItemParams{
		HTTPClient: client,
	}
}

/*
CatalogItemServiceGetCatalogItemParams contains all the parameters to send to the API endpoint

	for the catalog item service get catalog item operation.

	Typically these are written to a http.Request.
*/
type CatalogItemServiceGetCatalogItemParams struct {

	// Body.
	Body *models.V1GetCatalogItemRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the catalog item service get catalog item params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CatalogItemServiceGetCatalogItemParams) WithDefaults() *CatalogItemServiceGetCatalogItemParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the catalog item service get catalog item params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CatalogItemServiceGetCatalogItemParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the catalog item service get catalog item params
func (o *CatalogItemServiceGetCatalogItemParams) WithTimeout(timeout time.Duration) *CatalogItemServiceGetCatalogItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the catalog item service get catalog item params
func (o *CatalogItemServiceGetCatalogItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the catalog item service get catalog item params
func (o *CatalogItemServiceGetCatalogItemParams) WithContext(ctx context.Context) *CatalogItemServiceGetCatalogItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the catalog item service get catalog item params
func (o *CatalogItemServiceGetCatalogItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the catalog item service get catalog item params
func (o *CatalogItemServiceGetCatalogItemParams) WithHTTPClient(client *http.Client) *CatalogItemServiceGetCatalogItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the catalog item service get catalog item params
func (o *CatalogItemServiceGetCatalogItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the catalog item service get catalog item params
func (o *CatalogItemServiceGetCatalogItemParams) WithBody(body *models.V1GetCatalogItemRequest) *CatalogItemServiceGetCatalogItemParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the catalog item service get catalog item params
func (o *CatalogItemServiceGetCatalogItemParams) SetBody(body *models.V1GetCatalogItemRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CatalogItemServiceGetCatalogItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
