// Code generated by go-swagger; DO NOT EDIT.

package catalog_item_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCatalogItemServiceGetCatalogItem2Params creates a new CatalogItemServiceGetCatalogItem2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCatalogItemServiceGetCatalogItem2Params() *CatalogItemServiceGetCatalogItem2Params {
	return &CatalogItemServiceGetCatalogItem2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewCatalogItemServiceGetCatalogItem2ParamsWithTimeout creates a new CatalogItemServiceGetCatalogItem2Params object
// with the ability to set a timeout on a request.
func NewCatalogItemServiceGetCatalogItem2ParamsWithTimeout(timeout time.Duration) *CatalogItemServiceGetCatalogItem2Params {
	return &CatalogItemServiceGetCatalogItem2Params{
		timeout: timeout,
	}
}

// NewCatalogItemServiceGetCatalogItem2ParamsWithContext creates a new CatalogItemServiceGetCatalogItem2Params object
// with the ability to set a context for a request.
func NewCatalogItemServiceGetCatalogItem2ParamsWithContext(ctx context.Context) *CatalogItemServiceGetCatalogItem2Params {
	return &CatalogItemServiceGetCatalogItem2Params{
		Context: ctx,
	}
}

// NewCatalogItemServiceGetCatalogItem2ParamsWithHTTPClient creates a new CatalogItemServiceGetCatalogItem2Params object
// with the ability to set a custom HTTPClient for a request.
func NewCatalogItemServiceGetCatalogItem2ParamsWithHTTPClient(client *http.Client) *CatalogItemServiceGetCatalogItem2Params {
	return &CatalogItemServiceGetCatalogItem2Params{
		HTTPClient: client,
	}
}

/*
CatalogItemServiceGetCatalogItem2Params contains all the parameters to send to the API endpoint

	for the catalog item service get catalog item2 operation.

	Typically these are written to a http.Request.
*/
type CatalogItemServiceGetCatalogItem2Params struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the catalog item service get catalog item2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CatalogItemServiceGetCatalogItem2Params) WithDefaults() *CatalogItemServiceGetCatalogItem2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the catalog item service get catalog item2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CatalogItemServiceGetCatalogItem2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the catalog item service get catalog item2 params
func (o *CatalogItemServiceGetCatalogItem2Params) WithTimeout(timeout time.Duration) *CatalogItemServiceGetCatalogItem2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the catalog item service get catalog item2 params
func (o *CatalogItemServiceGetCatalogItem2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the catalog item service get catalog item2 params
func (o *CatalogItemServiceGetCatalogItem2Params) WithContext(ctx context.Context) *CatalogItemServiceGetCatalogItem2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the catalog item service get catalog item2 params
func (o *CatalogItemServiceGetCatalogItem2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the catalog item service get catalog item2 params
func (o *CatalogItemServiceGetCatalogItem2Params) WithHTTPClient(client *http.Client) *CatalogItemServiceGetCatalogItem2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the catalog item service get catalog item2 params
func (o *CatalogItemServiceGetCatalogItem2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the catalog item service get catalog item2 params
func (o *CatalogItemServiceGetCatalogItem2Params) WithID(id string) *CatalogItemServiceGetCatalogItem2Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the catalog item service get catalog item2 params
func (o *CatalogItemServiceGetCatalogItem2Params) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CatalogItemServiceGetCatalogItem2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := qrID
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
