// Code generated by go-swagger; DO NOT EDIT.

package amendment_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// AmendmentServiceListAmendments2Reader is a Reader for the AmendmentServiceListAmendments2 structure.
type AmendmentServiceListAmendments2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AmendmentServiceListAmendments2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAmendmentServiceListAmendments2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAmendmentServiceListAmendments2Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAmendmentServiceListAmendments2OK creates a AmendmentServiceListAmendments2OK with default headers values
func NewAmendmentServiceListAmendments2OK() *AmendmentServiceListAmendments2OK {
	return &AmendmentServiceListAmendments2OK{}
}

/*
AmendmentServiceListAmendments2OK describes a response with status code 200, with default header values.

A successful response.
*/
type AmendmentServiceListAmendments2OK struct {
	Payload *models.V1ListAmendmentsResponse
}

// IsSuccess returns true when this amendment service list amendments2 o k response has a 2xx status code
func (o *AmendmentServiceListAmendments2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this amendment service list amendments2 o k response has a 3xx status code
func (o *AmendmentServiceListAmendments2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this amendment service list amendments2 o k response has a 4xx status code
func (o *AmendmentServiceListAmendments2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this amendment service list amendments2 o k response has a 5xx status code
func (o *AmendmentServiceListAmendments2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this amendment service list amendments2 o k response a status code equal to that given
func (o *AmendmentServiceListAmendments2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the amendment service list amendments2 o k response
func (o *AmendmentServiceListAmendments2OK) Code() int {
	return 200
}

func (o *AmendmentServiceListAmendments2OK) Error() string {
	return fmt.Sprintf("[GET /v1/amendment/list][%d] amendmentServiceListAmendments2OK  %+v", 200, o.Payload)
}

func (o *AmendmentServiceListAmendments2OK) String() string {
	return fmt.Sprintf("[GET /v1/amendment/list][%d] amendmentServiceListAmendments2OK  %+v", 200, o.Payload)
}

func (o *AmendmentServiceListAmendments2OK) GetPayload() *models.V1ListAmendmentsResponse {
	return o.Payload
}

func (o *AmendmentServiceListAmendments2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ListAmendmentsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAmendmentServiceListAmendments2Default creates a AmendmentServiceListAmendments2Default with default headers values
func NewAmendmentServiceListAmendments2Default(code int) *AmendmentServiceListAmendments2Default {
	return &AmendmentServiceListAmendments2Default{
		_statusCode: code,
	}
}

/*
AmendmentServiceListAmendments2Default describes a response with status code -1, with default header values.

An unexpected error response.
*/
type AmendmentServiceListAmendments2Default struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this amendment service list amendments2 default response has a 2xx status code
func (o *AmendmentServiceListAmendments2Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this amendment service list amendments2 default response has a 3xx status code
func (o *AmendmentServiceListAmendments2Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this amendment service list amendments2 default response has a 4xx status code
func (o *AmendmentServiceListAmendments2Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this amendment service list amendments2 default response has a 5xx status code
func (o *AmendmentServiceListAmendments2Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this amendment service list amendments2 default response a status code equal to that given
func (o *AmendmentServiceListAmendments2Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the amendment service list amendments2 default response
func (o *AmendmentServiceListAmendments2Default) Code() int {
	return o._statusCode
}

func (o *AmendmentServiceListAmendments2Default) Error() string {
	return fmt.Sprintf("[GET /v1/amendment/list][%d] AmendmentService_ListAmendments2 default  %+v", o._statusCode, o.Payload)
}

func (o *AmendmentServiceListAmendments2Default) String() string {
	return fmt.Sprintf("[GET /v1/amendment/list][%d] AmendmentService_ListAmendments2 default  %+v", o._statusCode, o.Payload)
}

func (o *AmendmentServiceListAmendments2Default) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *AmendmentServiceListAmendments2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
