// Code generated by go-swagger; DO NOT EDIT.

package amendment_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// NewAmendmentServiceRenewContractItemParams creates a new AmendmentServiceRenewContractItemParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAmendmentServiceRenewContractItemParams() *AmendmentServiceRenewContractItemParams {
	return &AmendmentServiceRenewContractItemParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAmendmentServiceRenewContractItemParamsWithTimeout creates a new AmendmentServiceRenewContractItemParams object
// with the ability to set a timeout on a request.
func NewAmendmentServiceRenewContractItemParamsWithTimeout(timeout time.Duration) *AmendmentServiceRenewContractItemParams {
	return &AmendmentServiceRenewContractItemParams{
		timeout: timeout,
	}
}

// NewAmendmentServiceRenewContractItemParamsWithContext creates a new AmendmentServiceRenewContractItemParams object
// with the ability to set a context for a request.
func NewAmendmentServiceRenewContractItemParamsWithContext(ctx context.Context) *AmendmentServiceRenewContractItemParams {
	return &AmendmentServiceRenewContractItemParams{
		Context: ctx,
	}
}

// NewAmendmentServiceRenewContractItemParamsWithHTTPClient creates a new AmendmentServiceRenewContractItemParams object
// with the ability to set a custom HTTPClient for a request.
func NewAmendmentServiceRenewContractItemParamsWithHTTPClient(client *http.Client) *AmendmentServiceRenewContractItemParams {
	return &AmendmentServiceRenewContractItemParams{
		HTTPClient: client,
	}
}

/*
AmendmentServiceRenewContractItemParams contains all the parameters to send to the API endpoint

	for the amendment service renew contract item operation.

	Typically these are written to a http.Request.
*/
type AmendmentServiceRenewContractItemParams struct {

	// Body.
	Body *models.V1RenewContractItemRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the amendment service renew contract item params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AmendmentServiceRenewContractItemParams) WithDefaults() *AmendmentServiceRenewContractItemParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the amendment service renew contract item params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AmendmentServiceRenewContractItemParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the amendment service renew contract item params
func (o *AmendmentServiceRenewContractItemParams) WithTimeout(timeout time.Duration) *AmendmentServiceRenewContractItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the amendment service renew contract item params
func (o *AmendmentServiceRenewContractItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the amendment service renew contract item params
func (o *AmendmentServiceRenewContractItemParams) WithContext(ctx context.Context) *AmendmentServiceRenewContractItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the amendment service renew contract item params
func (o *AmendmentServiceRenewContractItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the amendment service renew contract item params
func (o *AmendmentServiceRenewContractItemParams) WithHTTPClient(client *http.Client) *AmendmentServiceRenewContractItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the amendment service renew contract item params
func (o *AmendmentServiceRenewContractItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the amendment service renew contract item params
func (o *AmendmentServiceRenewContractItemParams) WithBody(body *models.V1RenewContractItemRequest) *AmendmentServiceRenewContractItemParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the amendment service renew contract item params
func (o *AmendmentServiceRenewContractItemParams) SetBody(body *models.V1RenewContractItemRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AmendmentServiceRenewContractItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
