// Code generated by go-swagger; DO NOT EDIT.

package amendment_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// NewAmendmentServiceChangeQuantityParams creates a new AmendmentServiceChangeQuantityParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAmendmentServiceChangeQuantityParams() *AmendmentServiceChangeQuantityParams {
	return &AmendmentServiceChangeQuantityParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAmendmentServiceChangeQuantityParamsWithTimeout creates a new AmendmentServiceChangeQuantityParams object
// with the ability to set a timeout on a request.
func NewAmendmentServiceChangeQuantityParamsWithTimeout(timeout time.Duration) *AmendmentServiceChangeQuantityParams {
	return &AmendmentServiceChangeQuantityParams{
		timeout: timeout,
	}
}

// NewAmendmentServiceChangeQuantityParamsWithContext creates a new AmendmentServiceChangeQuantityParams object
// with the ability to set a context for a request.
func NewAmendmentServiceChangeQuantityParamsWithContext(ctx context.Context) *AmendmentServiceChangeQuantityParams {
	return &AmendmentServiceChangeQuantityParams{
		Context: ctx,
	}
}

// NewAmendmentServiceChangeQuantityParamsWithHTTPClient creates a new AmendmentServiceChangeQuantityParams object
// with the ability to set a custom HTTPClient for a request.
func NewAmendmentServiceChangeQuantityParamsWithHTTPClient(client *http.Client) *AmendmentServiceChangeQuantityParams {
	return &AmendmentServiceChangeQuantityParams{
		HTTPClient: client,
	}
}

/*
AmendmentServiceChangeQuantityParams contains all the parameters to send to the API endpoint

	for the amendment service change quantity operation.

	Typically these are written to a http.Request.
*/
type AmendmentServiceChangeQuantityParams struct {

	// Body.
	Body *models.V1ChangeQuantityRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the amendment service change quantity params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AmendmentServiceChangeQuantityParams) WithDefaults() *AmendmentServiceChangeQuantityParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the amendment service change quantity params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AmendmentServiceChangeQuantityParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the amendment service change quantity params
func (o *AmendmentServiceChangeQuantityParams) WithTimeout(timeout time.Duration) *AmendmentServiceChangeQuantityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the amendment service change quantity params
func (o *AmendmentServiceChangeQuantityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the amendment service change quantity params
func (o *AmendmentServiceChangeQuantityParams) WithContext(ctx context.Context) *AmendmentServiceChangeQuantityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the amendment service change quantity params
func (o *AmendmentServiceChangeQuantityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the amendment service change quantity params
func (o *AmendmentServiceChangeQuantityParams) WithHTTPClient(client *http.Client) *AmendmentServiceChangeQuantityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the amendment service change quantity params
func (o *AmendmentServiceChangeQuantityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the amendment service change quantity params
func (o *AmendmentServiceChangeQuantityParams) WithBody(body *models.V1ChangeQuantityRequest) *AmendmentServiceChangeQuantityParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the amendment service change quantity params
func (o *AmendmentServiceChangeQuantityParams) SetBody(body *models.V1ChangeQuantityRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AmendmentServiceChangeQuantityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
