// Code generated by go-swagger; DO NOT EDIT.

package customer_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// CustomerServiceGetCustomer2Reader is a Reader for the CustomerServiceGetCustomer2 structure.
type CustomerServiceGetCustomer2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerServiceGetCustomer2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerServiceGetCustomer2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerServiceGetCustomer2Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerServiceGetCustomer2OK creates a CustomerServiceGetCustomer2OK with default headers values
func NewCustomerServiceGetCustomer2OK() *CustomerServiceGetCustomer2OK {
	return &CustomerServiceGetCustomer2OK{}
}

/*
CustomerServiceGetCustomer2OK describes a response with status code 200, with default header values.

A successful response.
*/
type CustomerServiceGetCustomer2OK struct {
	Payload *models.V1GetCustomerResponse
}

// IsSuccess returns true when this customer service get customer2 o k response has a 2xx status code
func (o *CustomerServiceGetCustomer2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this customer service get customer2 o k response has a 3xx status code
func (o *CustomerServiceGetCustomer2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this customer service get customer2 o k response has a 4xx status code
func (o *CustomerServiceGetCustomer2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this customer service get customer2 o k response has a 5xx status code
func (o *CustomerServiceGetCustomer2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this customer service get customer2 o k response a status code equal to that given
func (o *CustomerServiceGetCustomer2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the customer service get customer2 o k response
func (o *CustomerServiceGetCustomer2OK) Code() int {
	return 200
}

func (o *CustomerServiceGetCustomer2OK) Error() string {
	return fmt.Sprintf("[GET /v1/customer/get][%d] customerServiceGetCustomer2OK  %+v", 200, o.Payload)
}

func (o *CustomerServiceGetCustomer2OK) String() string {
	return fmt.Sprintf("[GET /v1/customer/get][%d] customerServiceGetCustomer2OK  %+v", 200, o.Payload)
}

func (o *CustomerServiceGetCustomer2OK) GetPayload() *models.V1GetCustomerResponse {
	return o.Payload
}

func (o *CustomerServiceGetCustomer2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GetCustomerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerServiceGetCustomer2Default creates a CustomerServiceGetCustomer2Default with default headers values
func NewCustomerServiceGetCustomer2Default(code int) *CustomerServiceGetCustomer2Default {
	return &CustomerServiceGetCustomer2Default{
		_statusCode: code,
	}
}

/*
CustomerServiceGetCustomer2Default describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CustomerServiceGetCustomer2Default struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this customer service get customer2 default response has a 2xx status code
func (o *CustomerServiceGetCustomer2Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this customer service get customer2 default response has a 3xx status code
func (o *CustomerServiceGetCustomer2Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this customer service get customer2 default response has a 4xx status code
func (o *CustomerServiceGetCustomer2Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this customer service get customer2 default response has a 5xx status code
func (o *CustomerServiceGetCustomer2Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this customer service get customer2 default response a status code equal to that given
func (o *CustomerServiceGetCustomer2Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the customer service get customer2 default response
func (o *CustomerServiceGetCustomer2Default) Code() int {
	return o._statusCode
}

func (o *CustomerServiceGetCustomer2Default) Error() string {
	return fmt.Sprintf("[GET /v1/customer/get][%d] CustomerService_GetCustomer2 default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerServiceGetCustomer2Default) String() string {
	return fmt.Sprintf("[GET /v1/customer/get][%d] CustomerService_GetCustomer2 default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerServiceGetCustomer2Default) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *CustomerServiceGetCustomer2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
