// Code generated by go-swagger; DO NOT EDIT.

package customer_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// CustomerServiceGetCustomerReader is a Reader for the CustomerServiceGetCustomer structure.
type CustomerServiceGetCustomerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerServiceGetCustomerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerServiceGetCustomerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerServiceGetCustomerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerServiceGetCustomerOK creates a CustomerServiceGetCustomerOK with default headers values
func NewCustomerServiceGetCustomerOK() *CustomerServiceGetCustomerOK {
	return &CustomerServiceGetCustomerOK{}
}

/*
CustomerServiceGetCustomerOK describes a response with status code 200, with default header values.

A successful response.
*/
type CustomerServiceGetCustomerOK struct {
	Payload *models.V1GetCustomerResponse
}

// IsSuccess returns true when this customer service get customer o k response has a 2xx status code
func (o *CustomerServiceGetCustomerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this customer service get customer o k response has a 3xx status code
func (o *CustomerServiceGetCustomerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this customer service get customer o k response has a 4xx status code
func (o *CustomerServiceGetCustomerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this customer service get customer o k response has a 5xx status code
func (o *CustomerServiceGetCustomerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this customer service get customer o k response a status code equal to that given
func (o *CustomerServiceGetCustomerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the customer service get customer o k response
func (o *CustomerServiceGetCustomerOK) Code() int {
	return 200
}

func (o *CustomerServiceGetCustomerOK) Error() string {
	return fmt.Sprintf("[POST /v1/customer/get][%d] customerServiceGetCustomerOK  %+v", 200, o.Payload)
}

func (o *CustomerServiceGetCustomerOK) String() string {
	return fmt.Sprintf("[POST /v1/customer/get][%d] customerServiceGetCustomerOK  %+v", 200, o.Payload)
}

func (o *CustomerServiceGetCustomerOK) GetPayload() *models.V1GetCustomerResponse {
	return o.Payload
}

func (o *CustomerServiceGetCustomerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GetCustomerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerServiceGetCustomerDefault creates a CustomerServiceGetCustomerDefault with default headers values
func NewCustomerServiceGetCustomerDefault(code int) *CustomerServiceGetCustomerDefault {
	return &CustomerServiceGetCustomerDefault{
		_statusCode: code,
	}
}

/*
CustomerServiceGetCustomerDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CustomerServiceGetCustomerDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this customer service get customer default response has a 2xx status code
func (o *CustomerServiceGetCustomerDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this customer service get customer default response has a 3xx status code
func (o *CustomerServiceGetCustomerDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this customer service get customer default response has a 4xx status code
func (o *CustomerServiceGetCustomerDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this customer service get customer default response has a 5xx status code
func (o *CustomerServiceGetCustomerDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this customer service get customer default response a status code equal to that given
func (o *CustomerServiceGetCustomerDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the customer service get customer default response
func (o *CustomerServiceGetCustomerDefault) Code() int {
	return o._statusCode
}

func (o *CustomerServiceGetCustomerDefault) Error() string {
	return fmt.Sprintf("[POST /v1/customer/get][%d] CustomerService_GetCustomer default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerServiceGetCustomerDefault) String() string {
	return fmt.Sprintf("[POST /v1/customer/get][%d] CustomerService_GetCustomer default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerServiceGetCustomerDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *CustomerServiceGetCustomerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
