// Code generated by go-swagger; DO NOT EDIT.

package customer_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// CustomerServiceListCustomersReader is a Reader for the CustomerServiceListCustomers structure.
type CustomerServiceListCustomersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerServiceListCustomersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerServiceListCustomersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerServiceListCustomersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerServiceListCustomersOK creates a CustomerServiceListCustomersOK with default headers values
func NewCustomerServiceListCustomersOK() *CustomerServiceListCustomersOK {
	return &CustomerServiceListCustomersOK{}
}

/*
CustomerServiceListCustomersOK describes a response with status code 200, with default header values.

A successful response.
*/
type CustomerServiceListCustomersOK struct {
	Payload *models.V1ListCustomersResponse
}

// IsSuccess returns true when this customer service list customers o k response has a 2xx status code
func (o *CustomerServiceListCustomersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this customer service list customers o k response has a 3xx status code
func (o *CustomerServiceListCustomersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this customer service list customers o k response has a 4xx status code
func (o *CustomerServiceListCustomersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this customer service list customers o k response has a 5xx status code
func (o *CustomerServiceListCustomersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this customer service list customers o k response a status code equal to that given
func (o *CustomerServiceListCustomersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the customer service list customers o k response
func (o *CustomerServiceListCustomersOK) Code() int {
	return 200
}

func (o *CustomerServiceListCustomersOK) Error() string {
	return fmt.Sprintf("[POST /v1/customer/list][%d] customerServiceListCustomersOK  %+v", 200, o.Payload)
}

func (o *CustomerServiceListCustomersOK) String() string {
	return fmt.Sprintf("[POST /v1/customer/list][%d] customerServiceListCustomersOK  %+v", 200, o.Payload)
}

func (o *CustomerServiceListCustomersOK) GetPayload() *models.V1ListCustomersResponse {
	return o.Payload
}

func (o *CustomerServiceListCustomersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ListCustomersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerServiceListCustomersDefault creates a CustomerServiceListCustomersDefault with default headers values
func NewCustomerServiceListCustomersDefault(code int) *CustomerServiceListCustomersDefault {
	return &CustomerServiceListCustomersDefault{
		_statusCode: code,
	}
}

/*
CustomerServiceListCustomersDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CustomerServiceListCustomersDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this customer service list customers default response has a 2xx status code
func (o *CustomerServiceListCustomersDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this customer service list customers default response has a 3xx status code
func (o *CustomerServiceListCustomersDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this customer service list customers default response has a 4xx status code
func (o *CustomerServiceListCustomersDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this customer service list customers default response has a 5xx status code
func (o *CustomerServiceListCustomersDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this customer service list customers default response a status code equal to that given
func (o *CustomerServiceListCustomersDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the customer service list customers default response
func (o *CustomerServiceListCustomersDefault) Code() int {
	return o._statusCode
}

func (o *CustomerServiceListCustomersDefault) Error() string {
	return fmt.Sprintf("[POST /v1/customer/list][%d] CustomerService_ListCustomers default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerServiceListCustomersDefault) String() string {
	return fmt.Sprintf("[POST /v1/customer/list][%d] CustomerService_ListCustomers default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerServiceListCustomersDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *CustomerServiceListCustomersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
