// Code generated by go-swagger; DO NOT EDIT.

package customer_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// NewCustomerServiceCreateCustomerParams creates a new CustomerServiceCreateCustomerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerServiceCreateCustomerParams() *CustomerServiceCreateCustomerParams {
	return &CustomerServiceCreateCustomerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerServiceCreateCustomerParamsWithTimeout creates a new CustomerServiceCreateCustomerParams object
// with the ability to set a timeout on a request.
func NewCustomerServiceCreateCustomerParamsWithTimeout(timeout time.Duration) *CustomerServiceCreateCustomerParams {
	return &CustomerServiceCreateCustomerParams{
		timeout: timeout,
	}
}

// NewCustomerServiceCreateCustomerParamsWithContext creates a new CustomerServiceCreateCustomerParams object
// with the ability to set a context for a request.
func NewCustomerServiceCreateCustomerParamsWithContext(ctx context.Context) *CustomerServiceCreateCustomerParams {
	return &CustomerServiceCreateCustomerParams{
		Context: ctx,
	}
}

// NewCustomerServiceCreateCustomerParamsWithHTTPClient creates a new CustomerServiceCreateCustomerParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerServiceCreateCustomerParamsWithHTTPClient(client *http.Client) *CustomerServiceCreateCustomerParams {
	return &CustomerServiceCreateCustomerParams{
		HTTPClient: client,
	}
}

/*
CustomerServiceCreateCustomerParams contains all the parameters to send to the API endpoint

	for the customer service create customer operation.

	Typically these are written to a http.Request.
*/
type CustomerServiceCreateCustomerParams struct {

	// Body.
	Body *models.V1CreateCustomerRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer service create customer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerServiceCreateCustomerParams) WithDefaults() *CustomerServiceCreateCustomerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer service create customer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerServiceCreateCustomerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer service create customer params
func (o *CustomerServiceCreateCustomerParams) WithTimeout(timeout time.Duration) *CustomerServiceCreateCustomerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer service create customer params
func (o *CustomerServiceCreateCustomerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer service create customer params
func (o *CustomerServiceCreateCustomerParams) WithContext(ctx context.Context) *CustomerServiceCreateCustomerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer service create customer params
func (o *CustomerServiceCreateCustomerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer service create customer params
func (o *CustomerServiceCreateCustomerParams) WithHTTPClient(client *http.Client) *CustomerServiceCreateCustomerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer service create customer params
func (o *CustomerServiceCreateCustomerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the customer service create customer params
func (o *CustomerServiceCreateCustomerParams) WithBody(body *models.V1CreateCustomerRequest) *CustomerServiceCreateCustomerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the customer service create customer params
func (o *CustomerServiceCreateCustomerParams) SetBody(body *models.V1CreateCustomerRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerServiceCreateCustomerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
