// Code generated by go-swagger; DO NOT EDIT.

package expected_billing_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new expected billing service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for expected billing service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ExpectedBillingServiceListExpectedBillingsByContract(params *ExpectedBillingServiceListExpectedBillingsByContractParams, opts ...ClientOption) (*ExpectedBillingServiceListExpectedBillingsByContractOK, error)

	ExpectedBillingServiceListExpectedBillingsByContract2(params *ExpectedBillingServiceListExpectedBillingsByContract2Params, opts ...ClientOption) (*ExpectedBillingServiceListExpectedBillingsByContract2OK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
ExpectedBillingServiceListExpectedBillingsByContract 請求予定の一覧取得s

契約に紐づく請求予定一覧
*/
func (a *Client) ExpectedBillingServiceListExpectedBillingsByContract(params *ExpectedBillingServiceListExpectedBillingsByContractParams, opts ...ClientOption) (*ExpectedBillingServiceListExpectedBillingsByContractOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewExpectedBillingServiceListExpectedBillingsByContractParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ExpectedBillingService_ListExpectedBillingsByContract",
		Method:             "POST",
		PathPattern:        "/v1/expectedbilling/listbycontract",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ExpectedBillingServiceListExpectedBillingsByContractReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ExpectedBillingServiceListExpectedBillingsByContractOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ExpectedBillingServiceListExpectedBillingsByContractDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ExpectedBillingServiceListExpectedBillingsByContract2 請求予定の一覧取得s

契約に紐づく請求予定一覧
*/
func (a *Client) ExpectedBillingServiceListExpectedBillingsByContract2(params *ExpectedBillingServiceListExpectedBillingsByContract2Params, opts ...ClientOption) (*ExpectedBillingServiceListExpectedBillingsByContract2OK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewExpectedBillingServiceListExpectedBillingsByContract2Params()
	}
	op := &runtime.ClientOperation{
		ID:                 "ExpectedBillingService_ListExpectedBillingsByContract2",
		Method:             "GET",
		PathPattern:        "/v1/expectedbilling/listbycontract",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ExpectedBillingServiceListExpectedBillingsByContract2Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ExpectedBillingServiceListExpectedBillingsByContract2OK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ExpectedBillingServiceListExpectedBillingsByContract2Default)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
