// Code generated by go-swagger; DO NOT EDIT.

package usage_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new usage service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for usage service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	UsageServiceUpsertDailyUsage(params *UsageServiceUpsertDailyUsageParams, opts ...ClientOption) (*UsageServiceUpsertDailyUsageOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
UsageServiceUpsertDailyUsage 使用量s 日毎 の更新

指定した使用量を作成or更新します。
*/
func (a *Client) UsageServiceUpsertDailyUsage(params *UsageServiceUpsertDailyUsageParams, opts ...ClientOption) (*UsageServiceUpsertDailyUsageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUsageServiceUpsertDailyUsageParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UsageService_UpsertDailyUsage",
		Method:             "POST",
		PathPattern:        "/v1/usage/daily/upsert",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UsageServiceUpsertDailyUsageReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UsageServiceUpsertDailyUsageOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*UsageServiceUpsertDailyUsageDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
