// Code generated by go-swagger; DO NOT EDIT.

package contract_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// ContractServiceListContractsByCustomer4Reader is a Reader for the ContractServiceListContractsByCustomer4 structure.
type ContractServiceListContractsByCustomer4Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContractServiceListContractsByCustomer4Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewContractServiceListContractsByCustomer4OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewContractServiceListContractsByCustomer4Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewContractServiceListContractsByCustomer4OK creates a ContractServiceListContractsByCustomer4OK with default headers values
func NewContractServiceListContractsByCustomer4OK() *ContractServiceListContractsByCustomer4OK {
	return &ContractServiceListContractsByCustomer4OK{}
}

/*
ContractServiceListContractsByCustomer4OK describes a response with status code 200, with default header values.

A successful response.
*/
type ContractServiceListContractsByCustomer4OK struct {
	Payload *models.V1ListContractsByCustomerResponse
}

// IsSuccess returns true when this contract service list contracts by customer4 o k response has a 2xx status code
func (o *ContractServiceListContractsByCustomer4OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this contract service list contracts by customer4 o k response has a 3xx status code
func (o *ContractServiceListContractsByCustomer4OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this contract service list contracts by customer4 o k response has a 4xx status code
func (o *ContractServiceListContractsByCustomer4OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this contract service list contracts by customer4 o k response has a 5xx status code
func (o *ContractServiceListContractsByCustomer4OK) IsServerError() bool {
	return false
}

// IsCode returns true when this contract service list contracts by customer4 o k response a status code equal to that given
func (o *ContractServiceListContractsByCustomer4OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the contract service list contracts by customer4 o k response
func (o *ContractServiceListContractsByCustomer4OK) Code() int {
	return 200
}

func (o *ContractServiceListContractsByCustomer4OK) Error() string {
	return fmt.Sprintf("[GET /v1/contract/listbycustomerid][%d] contractServiceListContractsByCustomer4OK  %+v", 200, o.Payload)
}

func (o *ContractServiceListContractsByCustomer4OK) String() string {
	return fmt.Sprintf("[GET /v1/contract/listbycustomerid][%d] contractServiceListContractsByCustomer4OK  %+v", 200, o.Payload)
}

func (o *ContractServiceListContractsByCustomer4OK) GetPayload() *models.V1ListContractsByCustomerResponse {
	return o.Payload
}

func (o *ContractServiceListContractsByCustomer4OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ListContractsByCustomerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContractServiceListContractsByCustomer4Default creates a ContractServiceListContractsByCustomer4Default with default headers values
func NewContractServiceListContractsByCustomer4Default(code int) *ContractServiceListContractsByCustomer4Default {
	return &ContractServiceListContractsByCustomer4Default{
		_statusCode: code,
	}
}

/*
ContractServiceListContractsByCustomer4Default describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ContractServiceListContractsByCustomer4Default struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this contract service list contracts by customer4 default response has a 2xx status code
func (o *ContractServiceListContractsByCustomer4Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this contract service list contracts by customer4 default response has a 3xx status code
func (o *ContractServiceListContractsByCustomer4Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this contract service list contracts by customer4 default response has a 4xx status code
func (o *ContractServiceListContractsByCustomer4Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this contract service list contracts by customer4 default response has a 5xx status code
func (o *ContractServiceListContractsByCustomer4Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this contract service list contracts by customer4 default response a status code equal to that given
func (o *ContractServiceListContractsByCustomer4Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the contract service list contracts by customer4 default response
func (o *ContractServiceListContractsByCustomer4Default) Code() int {
	return o._statusCode
}

func (o *ContractServiceListContractsByCustomer4Default) Error() string {
	return fmt.Sprintf("[GET /v1/contract/listbycustomerid][%d] ContractService_ListContractsByCustomer4 default  %+v", o._statusCode, o.Payload)
}

func (o *ContractServiceListContractsByCustomer4Default) String() string {
	return fmt.Sprintf("[GET /v1/contract/listbycustomerid][%d] ContractService_ListContractsByCustomer4 default  %+v", o._statusCode, o.Payload)
}

func (o *ContractServiceListContractsByCustomer4Default) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *ContractServiceListContractsByCustomer4Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
