// Code generated by go-swagger; DO NOT EDIT.

package contract_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewContractServiceListContractsByCustomer4Params creates a new ContractServiceListContractsByCustomer4Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewContractServiceListContractsByCustomer4Params() *ContractServiceListContractsByCustomer4Params {
	return &ContractServiceListContractsByCustomer4Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewContractServiceListContractsByCustomer4ParamsWithTimeout creates a new ContractServiceListContractsByCustomer4Params object
// with the ability to set a timeout on a request.
func NewContractServiceListContractsByCustomer4ParamsWithTimeout(timeout time.Duration) *ContractServiceListContractsByCustomer4Params {
	return &ContractServiceListContractsByCustomer4Params{
		timeout: timeout,
	}
}

// NewContractServiceListContractsByCustomer4ParamsWithContext creates a new ContractServiceListContractsByCustomer4Params object
// with the ability to set a context for a request.
func NewContractServiceListContractsByCustomer4ParamsWithContext(ctx context.Context) *ContractServiceListContractsByCustomer4Params {
	return &ContractServiceListContractsByCustomer4Params{
		Context: ctx,
	}
}

// NewContractServiceListContractsByCustomer4ParamsWithHTTPClient creates a new ContractServiceListContractsByCustomer4Params object
// with the ability to set a custom HTTPClient for a request.
func NewContractServiceListContractsByCustomer4ParamsWithHTTPClient(client *http.Client) *ContractServiceListContractsByCustomer4Params {
	return &ContractServiceListContractsByCustomer4Params{
		HTTPClient: client,
	}
}

/*
ContractServiceListContractsByCustomer4Params contains all the parameters to send to the API endpoint

	for the contract service list contracts by customer4 operation.

	Typically these are written to a http.Request.
*/
type ContractServiceListContractsByCustomer4Params struct {

	/* CustomerID.

	   顧客ID
	*/
	CustomerID string

	/* CustomerOptionalID.

	   顧客管理ID(顧客IDの代わりに指定可)
	*/
	CustomerOptionalID *string

	/* PageSize.

	   一覧取得する最大数

	   Format: int32
	*/
	PageSize *int32

	/* PageToken.

	   一覧取得に使用するトークン
	*/
	PageToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the contract service list contracts by customer4 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContractServiceListContractsByCustomer4Params) WithDefaults() *ContractServiceListContractsByCustomer4Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the contract service list contracts by customer4 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContractServiceListContractsByCustomer4Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the contract service list contracts by customer4 params
func (o *ContractServiceListContractsByCustomer4Params) WithTimeout(timeout time.Duration) *ContractServiceListContractsByCustomer4Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the contract service list contracts by customer4 params
func (o *ContractServiceListContractsByCustomer4Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the contract service list contracts by customer4 params
func (o *ContractServiceListContractsByCustomer4Params) WithContext(ctx context.Context) *ContractServiceListContractsByCustomer4Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the contract service list contracts by customer4 params
func (o *ContractServiceListContractsByCustomer4Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the contract service list contracts by customer4 params
func (o *ContractServiceListContractsByCustomer4Params) WithHTTPClient(client *http.Client) *ContractServiceListContractsByCustomer4Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the contract service list contracts by customer4 params
func (o *ContractServiceListContractsByCustomer4Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the contract service list contracts by customer4 params
func (o *ContractServiceListContractsByCustomer4Params) WithCustomerID(customerID string) *ContractServiceListContractsByCustomer4Params {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the contract service list contracts by customer4 params
func (o *ContractServiceListContractsByCustomer4Params) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WithCustomerOptionalID adds the customerOptionalID to the contract service list contracts by customer4 params
func (o *ContractServiceListContractsByCustomer4Params) WithCustomerOptionalID(customerOptionalID *string) *ContractServiceListContractsByCustomer4Params {
	o.SetCustomerOptionalID(customerOptionalID)
	return o
}

// SetCustomerOptionalID adds the customerOptionalId to the contract service list contracts by customer4 params
func (o *ContractServiceListContractsByCustomer4Params) SetCustomerOptionalID(customerOptionalID *string) {
	o.CustomerOptionalID = customerOptionalID
}

// WithPageSize adds the pageSize to the contract service list contracts by customer4 params
func (o *ContractServiceListContractsByCustomer4Params) WithPageSize(pageSize *int32) *ContractServiceListContractsByCustomer4Params {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the contract service list contracts by customer4 params
func (o *ContractServiceListContractsByCustomer4Params) SetPageSize(pageSize *int32) {
	o.PageSize = pageSize
}

// WithPageToken adds the pageToken to the contract service list contracts by customer4 params
func (o *ContractServiceListContractsByCustomer4Params) WithPageToken(pageToken *string) *ContractServiceListContractsByCustomer4Params {
	o.SetPageToken(pageToken)
	return o
}

// SetPageToken adds the pageToken to the contract service list contracts by customer4 params
func (o *ContractServiceListContractsByCustomer4Params) SetPageToken(pageToken *string) {
	o.PageToken = pageToken
}

// WriteToRequest writes these params to a swagger request
func (o *ContractServiceListContractsByCustomer4Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param customerId
	qrCustomerID := o.CustomerID
	qCustomerID := qrCustomerID
	if qCustomerID != "" {

		if err := r.SetQueryParam("customerId", qCustomerID); err != nil {
			return err
		}
	}

	if o.CustomerOptionalID != nil {

		// query param customerOptionalId
		var qrCustomerOptionalID string

		if o.CustomerOptionalID != nil {
			qrCustomerOptionalID = *o.CustomerOptionalID
		}
		qCustomerOptionalID := qrCustomerOptionalID
		if qCustomerOptionalID != "" {

			if err := r.SetQueryParam("customerOptionalId", qCustomerOptionalID); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param pageSize
		var qrPageSize int32

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt32(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("pageSize", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.PageToken != nil {

		// query param pageToken
		var qrPageToken string

		if o.PageToken != nil {
			qrPageToken = *o.PageToken
		}
		qPageToken := qrPageToken
		if qPageToken != "" {

			if err := r.SetQueryParam("pageToken", qPageToken); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
