// Code generated by go-swagger; DO NOT EDIT.

package contract_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// NewContractServiceCreateContractParams creates a new ContractServiceCreateContractParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewContractServiceCreateContractParams() *ContractServiceCreateContractParams {
	return &ContractServiceCreateContractParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewContractServiceCreateContractParamsWithTimeout creates a new ContractServiceCreateContractParams object
// with the ability to set a timeout on a request.
func NewContractServiceCreateContractParamsWithTimeout(timeout time.Duration) *ContractServiceCreateContractParams {
	return &ContractServiceCreateContractParams{
		timeout: timeout,
	}
}

// NewContractServiceCreateContractParamsWithContext creates a new ContractServiceCreateContractParams object
// with the ability to set a context for a request.
func NewContractServiceCreateContractParamsWithContext(ctx context.Context) *ContractServiceCreateContractParams {
	return &ContractServiceCreateContractParams{
		Context: ctx,
	}
}

// NewContractServiceCreateContractParamsWithHTTPClient creates a new ContractServiceCreateContractParams object
// with the ability to set a custom HTTPClient for a request.
func NewContractServiceCreateContractParamsWithHTTPClient(client *http.Client) *ContractServiceCreateContractParams {
	return &ContractServiceCreateContractParams{
		HTTPClient: client,
	}
}

/*
ContractServiceCreateContractParams contains all the parameters to send to the API endpoint

	for the contract service create contract operation.

	Typically these are written to a http.Request.
*/
type ContractServiceCreateContractParams struct {

	// Body.
	Body *models.V1CreateContractRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the contract service create contract params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContractServiceCreateContractParams) WithDefaults() *ContractServiceCreateContractParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the contract service create contract params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContractServiceCreateContractParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the contract service create contract params
func (o *ContractServiceCreateContractParams) WithTimeout(timeout time.Duration) *ContractServiceCreateContractParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the contract service create contract params
func (o *ContractServiceCreateContractParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the contract service create contract params
func (o *ContractServiceCreateContractParams) WithContext(ctx context.Context) *ContractServiceCreateContractParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the contract service create contract params
func (o *ContractServiceCreateContractParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the contract service create contract params
func (o *ContractServiceCreateContractParams) WithHTTPClient(client *http.Client) *ContractServiceCreateContractParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the contract service create contract params
func (o *ContractServiceCreateContractParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the contract service create contract params
func (o *ContractServiceCreateContractParams) WithBody(body *models.V1CreateContractRequest) *ContractServiceCreateContractParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the contract service create contract params
func (o *ContractServiceCreateContractParams) SetBody(body *models.V1CreateContractRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ContractServiceCreateContractParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
