// Code generated by go-swagger; DO NOT EDIT.

package contract_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// NewContractServiceListContractsByCustomer3Params creates a new ContractServiceListContractsByCustomer3Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewContractServiceListContractsByCustomer3Params() *ContractServiceListContractsByCustomer3Params {
	return &ContractServiceListContractsByCustomer3Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewContractServiceListContractsByCustomer3ParamsWithTimeout creates a new ContractServiceListContractsByCustomer3Params object
// with the ability to set a timeout on a request.
func NewContractServiceListContractsByCustomer3ParamsWithTimeout(timeout time.Duration) *ContractServiceListContractsByCustomer3Params {
	return &ContractServiceListContractsByCustomer3Params{
		timeout: timeout,
	}
}

// NewContractServiceListContractsByCustomer3ParamsWithContext creates a new ContractServiceListContractsByCustomer3Params object
// with the ability to set a context for a request.
func NewContractServiceListContractsByCustomer3ParamsWithContext(ctx context.Context) *ContractServiceListContractsByCustomer3Params {
	return &ContractServiceListContractsByCustomer3Params{
		Context: ctx,
	}
}

// NewContractServiceListContractsByCustomer3ParamsWithHTTPClient creates a new ContractServiceListContractsByCustomer3Params object
// with the ability to set a custom HTTPClient for a request.
func NewContractServiceListContractsByCustomer3ParamsWithHTTPClient(client *http.Client) *ContractServiceListContractsByCustomer3Params {
	return &ContractServiceListContractsByCustomer3Params{
		HTTPClient: client,
	}
}

/*
ContractServiceListContractsByCustomer3Params contains all the parameters to send to the API endpoint

	for the contract service list contracts by customer3 operation.

	Typically these are written to a http.Request.
*/
type ContractServiceListContractsByCustomer3Params struct {

	// Body.
	Body *models.V1ListContractsByCustomerRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the contract service list contracts by customer3 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContractServiceListContractsByCustomer3Params) WithDefaults() *ContractServiceListContractsByCustomer3Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the contract service list contracts by customer3 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContractServiceListContractsByCustomer3Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the contract service list contracts by customer3 params
func (o *ContractServiceListContractsByCustomer3Params) WithTimeout(timeout time.Duration) *ContractServiceListContractsByCustomer3Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the contract service list contracts by customer3 params
func (o *ContractServiceListContractsByCustomer3Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the contract service list contracts by customer3 params
func (o *ContractServiceListContractsByCustomer3Params) WithContext(ctx context.Context) *ContractServiceListContractsByCustomer3Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the contract service list contracts by customer3 params
func (o *ContractServiceListContractsByCustomer3Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the contract service list contracts by customer3 params
func (o *ContractServiceListContractsByCustomer3Params) WithHTTPClient(client *http.Client) *ContractServiceListContractsByCustomer3Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the contract service list contracts by customer3 params
func (o *ContractServiceListContractsByCustomer3Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the contract service list contracts by customer3 params
func (o *ContractServiceListContractsByCustomer3Params) WithBody(body *models.V1ListContractsByCustomerRequest) *ContractServiceListContractsByCustomer3Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the contract service list contracts by customer3 params
func (o *ContractServiceListContractsByCustomer3Params) SetBody(body *models.V1ListContractsByCustomerRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ContractServiceListContractsByCustomer3Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
