// Code generated by go-swagger; DO NOT EDIT.

package contract_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// ContractServiceListContractsByCustomer2Reader is a Reader for the ContractServiceListContractsByCustomer2 structure.
type ContractServiceListContractsByCustomer2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContractServiceListContractsByCustomer2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewContractServiceListContractsByCustomer2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewContractServiceListContractsByCustomer2Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewContractServiceListContractsByCustomer2OK creates a ContractServiceListContractsByCustomer2OK with default headers values
func NewContractServiceListContractsByCustomer2OK() *ContractServiceListContractsByCustomer2OK {
	return &ContractServiceListContractsByCustomer2OK{}
}

/*
ContractServiceListContractsByCustomer2OK describes a response with status code 200, with default header values.

A successful response.
*/
type ContractServiceListContractsByCustomer2OK struct {
	Payload *models.V1ListContractsByCustomerResponse
}

// IsSuccess returns true when this contract service list contracts by customer2 o k response has a 2xx status code
func (o *ContractServiceListContractsByCustomer2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this contract service list contracts by customer2 o k response has a 3xx status code
func (o *ContractServiceListContractsByCustomer2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this contract service list contracts by customer2 o k response has a 4xx status code
func (o *ContractServiceListContractsByCustomer2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this contract service list contracts by customer2 o k response has a 5xx status code
func (o *ContractServiceListContractsByCustomer2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this contract service list contracts by customer2 o k response a status code equal to that given
func (o *ContractServiceListContractsByCustomer2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the contract service list contracts by customer2 o k response
func (o *ContractServiceListContractsByCustomer2OK) Code() int {
	return 200
}

func (o *ContractServiceListContractsByCustomer2OK) Error() string {
	return fmt.Sprintf("[GET /v1/contract/listbycustomer][%d] contractServiceListContractsByCustomer2OK  %+v", 200, o.Payload)
}

func (o *ContractServiceListContractsByCustomer2OK) String() string {
	return fmt.Sprintf("[GET /v1/contract/listbycustomer][%d] contractServiceListContractsByCustomer2OK  %+v", 200, o.Payload)
}

func (o *ContractServiceListContractsByCustomer2OK) GetPayload() *models.V1ListContractsByCustomerResponse {
	return o.Payload
}

func (o *ContractServiceListContractsByCustomer2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ListContractsByCustomerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContractServiceListContractsByCustomer2Default creates a ContractServiceListContractsByCustomer2Default with default headers values
func NewContractServiceListContractsByCustomer2Default(code int) *ContractServiceListContractsByCustomer2Default {
	return &ContractServiceListContractsByCustomer2Default{
		_statusCode: code,
	}
}

/*
ContractServiceListContractsByCustomer2Default describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ContractServiceListContractsByCustomer2Default struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this contract service list contracts by customer2 default response has a 2xx status code
func (o *ContractServiceListContractsByCustomer2Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this contract service list contracts by customer2 default response has a 3xx status code
func (o *ContractServiceListContractsByCustomer2Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this contract service list contracts by customer2 default response has a 4xx status code
func (o *ContractServiceListContractsByCustomer2Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this contract service list contracts by customer2 default response has a 5xx status code
func (o *ContractServiceListContractsByCustomer2Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this contract service list contracts by customer2 default response a status code equal to that given
func (o *ContractServiceListContractsByCustomer2Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the contract service list contracts by customer2 default response
func (o *ContractServiceListContractsByCustomer2Default) Code() int {
	return o._statusCode
}

func (o *ContractServiceListContractsByCustomer2Default) Error() string {
	return fmt.Sprintf("[GET /v1/contract/listbycustomer][%d] ContractService_ListContractsByCustomer2 default  %+v", o._statusCode, o.Payload)
}

func (o *ContractServiceListContractsByCustomer2Default) String() string {
	return fmt.Sprintf("[GET /v1/contract/listbycustomer][%d] ContractService_ListContractsByCustomer2 default  %+v", o._statusCode, o.Payload)
}

func (o *ContractServiceListContractsByCustomer2Default) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *ContractServiceListContractsByCustomer2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
