// Code generated by go-swagger; DO NOT EDIT.

package contract_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// NewContractServiceListContractsByCustomerParams creates a new ContractServiceListContractsByCustomerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewContractServiceListContractsByCustomerParams() *ContractServiceListContractsByCustomerParams {
	return &ContractServiceListContractsByCustomerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewContractServiceListContractsByCustomerParamsWithTimeout creates a new ContractServiceListContractsByCustomerParams object
// with the ability to set a timeout on a request.
func NewContractServiceListContractsByCustomerParamsWithTimeout(timeout time.Duration) *ContractServiceListContractsByCustomerParams {
	return &ContractServiceListContractsByCustomerParams{
		timeout: timeout,
	}
}

// NewContractServiceListContractsByCustomerParamsWithContext creates a new ContractServiceListContractsByCustomerParams object
// with the ability to set a context for a request.
func NewContractServiceListContractsByCustomerParamsWithContext(ctx context.Context) *ContractServiceListContractsByCustomerParams {
	return &ContractServiceListContractsByCustomerParams{
		Context: ctx,
	}
}

// NewContractServiceListContractsByCustomerParamsWithHTTPClient creates a new ContractServiceListContractsByCustomerParams object
// with the ability to set a custom HTTPClient for a request.
func NewContractServiceListContractsByCustomerParamsWithHTTPClient(client *http.Client) *ContractServiceListContractsByCustomerParams {
	return &ContractServiceListContractsByCustomerParams{
		HTTPClient: client,
	}
}

/*
ContractServiceListContractsByCustomerParams contains all the parameters to send to the API endpoint

	for the contract service list contracts by customer operation.

	Typically these are written to a http.Request.
*/
type ContractServiceListContractsByCustomerParams struct {

	// Body.
	Body *models.V1ListContractsByCustomerRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the contract service list contracts by customer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContractServiceListContractsByCustomerParams) WithDefaults() *ContractServiceListContractsByCustomerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the contract service list contracts by customer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContractServiceListContractsByCustomerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the contract service list contracts by customer params
func (o *ContractServiceListContractsByCustomerParams) WithTimeout(timeout time.Duration) *ContractServiceListContractsByCustomerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the contract service list contracts by customer params
func (o *ContractServiceListContractsByCustomerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the contract service list contracts by customer params
func (o *ContractServiceListContractsByCustomerParams) WithContext(ctx context.Context) *ContractServiceListContractsByCustomerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the contract service list contracts by customer params
func (o *ContractServiceListContractsByCustomerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the contract service list contracts by customer params
func (o *ContractServiceListContractsByCustomerParams) WithHTTPClient(client *http.Client) *ContractServiceListContractsByCustomerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the contract service list contracts by customer params
func (o *ContractServiceListContractsByCustomerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the contract service list contracts by customer params
func (o *ContractServiceListContractsByCustomerParams) WithBody(body *models.V1ListContractsByCustomerRequest) *ContractServiceListContractsByCustomerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the contract service list contracts by customer params
func (o *ContractServiceListContractsByCustomerParams) SetBody(body *models.V1ListContractsByCustomerRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ContractServiceListContractsByCustomerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
