// Code generated by go-swagger; DO NOT EDIT.

package customer_staff_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// NewCustomerStaffServiceGetCustomerStaffParams creates a new CustomerStaffServiceGetCustomerStaffParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerStaffServiceGetCustomerStaffParams() *CustomerStaffServiceGetCustomerStaffParams {
	return &CustomerStaffServiceGetCustomerStaffParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerStaffServiceGetCustomerStaffParamsWithTimeout creates a new CustomerStaffServiceGetCustomerStaffParams object
// with the ability to set a timeout on a request.
func NewCustomerStaffServiceGetCustomerStaffParamsWithTimeout(timeout time.Duration) *CustomerStaffServiceGetCustomerStaffParams {
	return &CustomerStaffServiceGetCustomerStaffParams{
		timeout: timeout,
	}
}

// NewCustomerStaffServiceGetCustomerStaffParamsWithContext creates a new CustomerStaffServiceGetCustomerStaffParams object
// with the ability to set a context for a request.
func NewCustomerStaffServiceGetCustomerStaffParamsWithContext(ctx context.Context) *CustomerStaffServiceGetCustomerStaffParams {
	return &CustomerStaffServiceGetCustomerStaffParams{
		Context: ctx,
	}
}

// NewCustomerStaffServiceGetCustomerStaffParamsWithHTTPClient creates a new CustomerStaffServiceGetCustomerStaffParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerStaffServiceGetCustomerStaffParamsWithHTTPClient(client *http.Client) *CustomerStaffServiceGetCustomerStaffParams {
	return &CustomerStaffServiceGetCustomerStaffParams{
		HTTPClient: client,
	}
}

/*
CustomerStaffServiceGetCustomerStaffParams contains all the parameters to send to the API endpoint

	for the customer staff service get customer staff operation.

	Typically these are written to a http.Request.
*/
type CustomerStaffServiceGetCustomerStaffParams struct {

	// Body.
	Body *models.V1GetCustomerStaffRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer staff service get customer staff params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerStaffServiceGetCustomerStaffParams) WithDefaults() *CustomerStaffServiceGetCustomerStaffParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer staff service get customer staff params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerStaffServiceGetCustomerStaffParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer staff service get customer staff params
func (o *CustomerStaffServiceGetCustomerStaffParams) WithTimeout(timeout time.Duration) *CustomerStaffServiceGetCustomerStaffParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer staff service get customer staff params
func (o *CustomerStaffServiceGetCustomerStaffParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer staff service get customer staff params
func (o *CustomerStaffServiceGetCustomerStaffParams) WithContext(ctx context.Context) *CustomerStaffServiceGetCustomerStaffParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer staff service get customer staff params
func (o *CustomerStaffServiceGetCustomerStaffParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer staff service get customer staff params
func (o *CustomerStaffServiceGetCustomerStaffParams) WithHTTPClient(client *http.Client) *CustomerStaffServiceGetCustomerStaffParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer staff service get customer staff params
func (o *CustomerStaffServiceGetCustomerStaffParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the customer staff service get customer staff params
func (o *CustomerStaffServiceGetCustomerStaffParams) WithBody(body *models.V1GetCustomerStaffRequest) *CustomerStaffServiceGetCustomerStaffParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the customer staff service get customer staff params
func (o *CustomerStaffServiceGetCustomerStaffParams) SetBody(body *models.V1GetCustomerStaffRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerStaffServiceGetCustomerStaffParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
