// Code generated by go-swagger; DO NOT EDIT.

package customer_staff_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCustomerStaffServiceGetCustomerStaff2Params creates a new CustomerStaffServiceGetCustomerStaff2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerStaffServiceGetCustomerStaff2Params() *CustomerStaffServiceGetCustomerStaff2Params {
	return &CustomerStaffServiceGetCustomerStaff2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerStaffServiceGetCustomerStaff2ParamsWithTimeout creates a new CustomerStaffServiceGetCustomerStaff2Params object
// with the ability to set a timeout on a request.
func NewCustomerStaffServiceGetCustomerStaff2ParamsWithTimeout(timeout time.Duration) *CustomerStaffServiceGetCustomerStaff2Params {
	return &CustomerStaffServiceGetCustomerStaff2Params{
		timeout: timeout,
	}
}

// NewCustomerStaffServiceGetCustomerStaff2ParamsWithContext creates a new CustomerStaffServiceGetCustomerStaff2Params object
// with the ability to set a context for a request.
func NewCustomerStaffServiceGetCustomerStaff2ParamsWithContext(ctx context.Context) *CustomerStaffServiceGetCustomerStaff2Params {
	return &CustomerStaffServiceGetCustomerStaff2Params{
		Context: ctx,
	}
}

// NewCustomerStaffServiceGetCustomerStaff2ParamsWithHTTPClient creates a new CustomerStaffServiceGetCustomerStaff2Params object
// with the ability to set a custom HTTPClient for a request.
func NewCustomerStaffServiceGetCustomerStaff2ParamsWithHTTPClient(client *http.Client) *CustomerStaffServiceGetCustomerStaff2Params {
	return &CustomerStaffServiceGetCustomerStaff2Params{
		HTTPClient: client,
	}
}

/*
CustomerStaffServiceGetCustomerStaff2Params contains all the parameters to send to the API endpoint

	for the customer staff service get customer staff2 operation.

	Typically these are written to a http.Request.
*/
type CustomerStaffServiceGetCustomerStaff2Params struct {

	/* CustomerID.

	   顧客ID
	*/
	CustomerID string

	/* CustomerOptionalID.

	   顧客管理ID(顧客IDの代わりに指定可)
	*/
	CustomerOptionalID *string

	/* ID.

	   顧客担当者ID
	*/
	ID string

	/* OptionalID.

	   顧客担当者管理ID(顧客担当者IDの代わりに指定可)
	*/
	OptionalID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer staff service get customer staff2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerStaffServiceGetCustomerStaff2Params) WithDefaults() *CustomerStaffServiceGetCustomerStaff2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer staff service get customer staff2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerStaffServiceGetCustomerStaff2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the customer staff service get customer staff2 params
func (o *CustomerStaffServiceGetCustomerStaff2Params) WithTimeout(timeout time.Duration) *CustomerStaffServiceGetCustomerStaff2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer staff service get customer staff2 params
func (o *CustomerStaffServiceGetCustomerStaff2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer staff service get customer staff2 params
func (o *CustomerStaffServiceGetCustomerStaff2Params) WithContext(ctx context.Context) *CustomerStaffServiceGetCustomerStaff2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer staff service get customer staff2 params
func (o *CustomerStaffServiceGetCustomerStaff2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the customer staff service get customer staff2 params
func (o *CustomerStaffServiceGetCustomerStaff2Params) WithHTTPClient(client *http.Client) *CustomerStaffServiceGetCustomerStaff2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the customer staff service get customer staff2 params
func (o *CustomerStaffServiceGetCustomerStaff2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the customer staff service get customer staff2 params
func (o *CustomerStaffServiceGetCustomerStaff2Params) WithCustomerID(customerID string) *CustomerStaffServiceGetCustomerStaff2Params {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the customer staff service get customer staff2 params
func (o *CustomerStaffServiceGetCustomerStaff2Params) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WithCustomerOptionalID adds the customerOptionalID to the customer staff service get customer staff2 params
func (o *CustomerStaffServiceGetCustomerStaff2Params) WithCustomerOptionalID(customerOptionalID *string) *CustomerStaffServiceGetCustomerStaff2Params {
	o.SetCustomerOptionalID(customerOptionalID)
	return o
}

// SetCustomerOptionalID adds the customerOptionalId to the customer staff service get customer staff2 params
func (o *CustomerStaffServiceGetCustomerStaff2Params) SetCustomerOptionalID(customerOptionalID *string) {
	o.CustomerOptionalID = customerOptionalID
}

// WithID adds the id to the customer staff service get customer staff2 params
func (o *CustomerStaffServiceGetCustomerStaff2Params) WithID(id string) *CustomerStaffServiceGetCustomerStaff2Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the customer staff service get customer staff2 params
func (o *CustomerStaffServiceGetCustomerStaff2Params) SetID(id string) {
	o.ID = id
}

// WithOptionalID adds the optionalID to the customer staff service get customer staff2 params
func (o *CustomerStaffServiceGetCustomerStaff2Params) WithOptionalID(optionalID *string) *CustomerStaffServiceGetCustomerStaff2Params {
	o.SetOptionalID(optionalID)
	return o
}

// SetOptionalID adds the optionalId to the customer staff service get customer staff2 params
func (o *CustomerStaffServiceGetCustomerStaff2Params) SetOptionalID(optionalID *string) {
	o.OptionalID = optionalID
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerStaffServiceGetCustomerStaff2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param customerId
	qrCustomerID := o.CustomerID
	qCustomerID := qrCustomerID
	if qCustomerID != "" {

		if err := r.SetQueryParam("customerId", qCustomerID); err != nil {
			return err
		}
	}

	if o.CustomerOptionalID != nil {

		// query param customerOptionalId
		var qrCustomerOptionalID string

		if o.CustomerOptionalID != nil {
			qrCustomerOptionalID = *o.CustomerOptionalID
		}
		qCustomerOptionalID := qrCustomerOptionalID
		if qCustomerOptionalID != "" {

			if err := r.SetQueryParam("customerOptionalId", qCustomerOptionalID); err != nil {
				return err
			}
		}
	}

	// query param id
	qrID := o.ID
	qID := qrID
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if o.OptionalID != nil {

		// query param optionalId
		var qrOptionalID string

		if o.OptionalID != nil {
			qrOptionalID = *o.OptionalID
		}
		qOptionalID := qrOptionalID
		if qOptionalID != "" {

			if err := r.SetQueryParam("optionalId", qOptionalID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
