// Code generated by go-swagger; DO NOT EDIT.

package customer_staff_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// CustomerStaffServiceGetCustomerStaffReader is a Reader for the CustomerStaffServiceGetCustomerStaff structure.
type CustomerStaffServiceGetCustomerStaffReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerStaffServiceGetCustomerStaffReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerStaffServiceGetCustomerStaffOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerStaffServiceGetCustomerStaffDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerStaffServiceGetCustomerStaffOK creates a CustomerStaffServiceGetCustomerStaffOK with default headers values
func NewCustomerStaffServiceGetCustomerStaffOK() *CustomerStaffServiceGetCustomerStaffOK {
	return &CustomerStaffServiceGetCustomerStaffOK{}
}

/*
CustomerStaffServiceGetCustomerStaffOK describes a response with status code 200, with default header values.

A successful response.
*/
type CustomerStaffServiceGetCustomerStaffOK struct {
	Payload *models.V1GetCustomerStaffResponse
}

// IsSuccess returns true when this customer staff service get customer staff o k response has a 2xx status code
func (o *CustomerStaffServiceGetCustomerStaffOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this customer staff service get customer staff o k response has a 3xx status code
func (o *CustomerStaffServiceGetCustomerStaffOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this customer staff service get customer staff o k response has a 4xx status code
func (o *CustomerStaffServiceGetCustomerStaffOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this customer staff service get customer staff o k response has a 5xx status code
func (o *CustomerStaffServiceGetCustomerStaffOK) IsServerError() bool {
	return false
}

// IsCode returns true when this customer staff service get customer staff o k response a status code equal to that given
func (o *CustomerStaffServiceGetCustomerStaffOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the customer staff service get customer staff o k response
func (o *CustomerStaffServiceGetCustomerStaffOK) Code() int {
	return 200
}

func (o *CustomerStaffServiceGetCustomerStaffOK) Error() string {
	return fmt.Sprintf("[POST /v1/customerstaff/get][%d] customerStaffServiceGetCustomerStaffOK  %+v", 200, o.Payload)
}

func (o *CustomerStaffServiceGetCustomerStaffOK) String() string {
	return fmt.Sprintf("[POST /v1/customerstaff/get][%d] customerStaffServiceGetCustomerStaffOK  %+v", 200, o.Payload)
}

func (o *CustomerStaffServiceGetCustomerStaffOK) GetPayload() *models.V1GetCustomerStaffResponse {
	return o.Payload
}

func (o *CustomerStaffServiceGetCustomerStaffOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GetCustomerStaffResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerStaffServiceGetCustomerStaffDefault creates a CustomerStaffServiceGetCustomerStaffDefault with default headers values
func NewCustomerStaffServiceGetCustomerStaffDefault(code int) *CustomerStaffServiceGetCustomerStaffDefault {
	return &CustomerStaffServiceGetCustomerStaffDefault{
		_statusCode: code,
	}
}

/*
CustomerStaffServiceGetCustomerStaffDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CustomerStaffServiceGetCustomerStaffDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this customer staff service get customer staff default response has a 2xx status code
func (o *CustomerStaffServiceGetCustomerStaffDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this customer staff service get customer staff default response has a 3xx status code
func (o *CustomerStaffServiceGetCustomerStaffDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this customer staff service get customer staff default response has a 4xx status code
func (o *CustomerStaffServiceGetCustomerStaffDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this customer staff service get customer staff default response has a 5xx status code
func (o *CustomerStaffServiceGetCustomerStaffDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this customer staff service get customer staff default response a status code equal to that given
func (o *CustomerStaffServiceGetCustomerStaffDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the customer staff service get customer staff default response
func (o *CustomerStaffServiceGetCustomerStaffDefault) Code() int {
	return o._statusCode
}

func (o *CustomerStaffServiceGetCustomerStaffDefault) Error() string {
	return fmt.Sprintf("[POST /v1/customerstaff/get][%d] CustomerStaffService_GetCustomerStaff default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerStaffServiceGetCustomerStaffDefault) String() string {
	return fmt.Sprintf("[POST /v1/customerstaff/get][%d] CustomerStaffService_GetCustomerStaff default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerStaffServiceGetCustomerStaffDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *CustomerStaffServiceGetCustomerStaffDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
