// Code generated by go-swagger; DO NOT EDIT.

package customer_staff_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kzmake/terraform-provider-scalebase/api/models"
)

// CustomerStaffServiceDeleteCustomerStaffReader is a Reader for the CustomerStaffServiceDeleteCustomerStaff structure.
type CustomerStaffServiceDeleteCustomerStaffReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerStaffServiceDeleteCustomerStaffReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomerStaffServiceDeleteCustomerStaffOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomerStaffServiceDeleteCustomerStaffDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomerStaffServiceDeleteCustomerStaffOK creates a CustomerStaffServiceDeleteCustomerStaffOK with default headers values
func NewCustomerStaffServiceDeleteCustomerStaffOK() *CustomerStaffServiceDeleteCustomerStaffOK {
	return &CustomerStaffServiceDeleteCustomerStaffOK{}
}

/*
CustomerStaffServiceDeleteCustomerStaffOK describes a response with status code 200, with default header values.

A successful response.
*/
type CustomerStaffServiceDeleteCustomerStaffOK struct {
	Payload models.V1DeleteCustomerStaffResponse
}

// IsSuccess returns true when this customer staff service delete customer staff o k response has a 2xx status code
func (o *CustomerStaffServiceDeleteCustomerStaffOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this customer staff service delete customer staff o k response has a 3xx status code
func (o *CustomerStaffServiceDeleteCustomerStaffOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this customer staff service delete customer staff o k response has a 4xx status code
func (o *CustomerStaffServiceDeleteCustomerStaffOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this customer staff service delete customer staff o k response has a 5xx status code
func (o *CustomerStaffServiceDeleteCustomerStaffOK) IsServerError() bool {
	return false
}

// IsCode returns true when this customer staff service delete customer staff o k response a status code equal to that given
func (o *CustomerStaffServiceDeleteCustomerStaffOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the customer staff service delete customer staff o k response
func (o *CustomerStaffServiceDeleteCustomerStaffOK) Code() int {
	return 200
}

func (o *CustomerStaffServiceDeleteCustomerStaffOK) Error() string {
	return fmt.Sprintf("[POST /v1/customerstaff/delete][%d] customerStaffServiceDeleteCustomerStaffOK  %+v", 200, o.Payload)
}

func (o *CustomerStaffServiceDeleteCustomerStaffOK) String() string {
	return fmt.Sprintf("[POST /v1/customerstaff/delete][%d] customerStaffServiceDeleteCustomerStaffOK  %+v", 200, o.Payload)
}

func (o *CustomerStaffServiceDeleteCustomerStaffOK) GetPayload() models.V1DeleteCustomerStaffResponse {
	return o.Payload
}

func (o *CustomerStaffServiceDeleteCustomerStaffOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomerStaffServiceDeleteCustomerStaffDefault creates a CustomerStaffServiceDeleteCustomerStaffDefault with default headers values
func NewCustomerStaffServiceDeleteCustomerStaffDefault(code int) *CustomerStaffServiceDeleteCustomerStaffDefault {
	return &CustomerStaffServiceDeleteCustomerStaffDefault{
		_statusCode: code,
	}
}

/*
CustomerStaffServiceDeleteCustomerStaffDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CustomerStaffServiceDeleteCustomerStaffDefault struct {
	_statusCode int

	Payload *models.GooglerpcStatus
}

// IsSuccess returns true when this customer staff service delete customer staff default response has a 2xx status code
func (o *CustomerStaffServiceDeleteCustomerStaffDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this customer staff service delete customer staff default response has a 3xx status code
func (o *CustomerStaffServiceDeleteCustomerStaffDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this customer staff service delete customer staff default response has a 4xx status code
func (o *CustomerStaffServiceDeleteCustomerStaffDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this customer staff service delete customer staff default response has a 5xx status code
func (o *CustomerStaffServiceDeleteCustomerStaffDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this customer staff service delete customer staff default response a status code equal to that given
func (o *CustomerStaffServiceDeleteCustomerStaffDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the customer staff service delete customer staff default response
func (o *CustomerStaffServiceDeleteCustomerStaffDefault) Code() int {
	return o._statusCode
}

func (o *CustomerStaffServiceDeleteCustomerStaffDefault) Error() string {
	return fmt.Sprintf("[POST /v1/customerstaff/delete][%d] CustomerStaffService_DeleteCustomerStaff default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerStaffServiceDeleteCustomerStaffDefault) String() string {
	return fmt.Sprintf("[POST /v1/customerstaff/delete][%d] CustomerStaffService_DeleteCustomerStaff default  %+v", o._statusCode, o.Payload)
}

func (o *CustomerStaffServiceDeleteCustomerStaffDefault) GetPayload() *models.GooglerpcStatus {
	return o.Payload
}

func (o *CustomerStaffServiceDeleteCustomerStaffDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
