// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// CreateCatalogItemRequestClosingDate create catalog item request closing date
//
// swagger:model CreateCatalogItemRequestClosingDate
type CreateCatalogItemRequestClosingDate string

func NewCreateCatalogItemRequestClosingDate(value CreateCatalogItemRequestClosingDate) *CreateCatalogItemRequestClosingDate {
	return &value
}

// Pointer returns a pointer to a freshly-allocated CreateCatalogItemRequestClosingDate.
func (m CreateCatalogItemRequestClosingDate) Pointer() *CreateCatalogItemRequestClosingDate {
	return &m
}

const (

	// CreateCatalogItemRequestClosingDateCLOSINGDATEDAY1 captures enum value "CLOSING_DATE_DAY_1"
	CreateCatalogItemRequestClosingDateCLOSINGDATEDAY1 CreateCatalogItemRequestClosingDate = "CLOSING_DATE_DAY_1"

	// CreateCatalogItemRequestClosingDateCLOSINGDATEDAY31 captures enum value "CLOSING_DATE_DAY_31"
	CreateCatalogItemRequestClosingDateCLOSINGDATEDAY31 CreateCatalogItemRequestClosingDate = "CLOSING_DATE_DAY_31"

	// CreateCatalogItemRequestClosingDateCLOSINGDATEFIRSTDAYOFMONTH captures enum value "CLOSING_DATE_FIRST_DAY_OF_MONTH"
	CreateCatalogItemRequestClosingDateCLOSINGDATEFIRSTDAYOFMONTH CreateCatalogItemRequestClosingDate = "CLOSING_DATE_FIRST_DAY_OF_MONTH"

	// CreateCatalogItemRequestClosingDateCLOSINGDATELASTDAYOFMONTH captures enum value "CLOSING_DATE_LAST_DAY_OF_MONTH"
	CreateCatalogItemRequestClosingDateCLOSINGDATELASTDAYOFMONTH CreateCatalogItemRequestClosingDate = "CLOSING_DATE_LAST_DAY_OF_MONTH"

	// CreateCatalogItemRequestClosingDateCLOSINGDATEONEDAYBEFORE captures enum value "CLOSING_DATE_ONE_DAY_BEFORE"
	CreateCatalogItemRequestClosingDateCLOSINGDATEONEDAYBEFORE CreateCatalogItemRequestClosingDate = "CLOSING_DATE_ONE_DAY_BEFORE"
)

// for schema
var createCatalogItemRequestClosingDateEnum []interface{}

func init() {
	var res []CreateCatalogItemRequestClosingDate
	if err := json.Unmarshal([]byte(`["CLOSING_DATE_DAY_1","CLOSING_DATE_DAY_31","CLOSING_DATE_FIRST_DAY_OF_MONTH","CLOSING_DATE_LAST_DAY_OF_MONTH","CLOSING_DATE_ONE_DAY_BEFORE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createCatalogItemRequestClosingDateEnum = append(createCatalogItemRequestClosingDateEnum, v)
	}
}

func (m CreateCatalogItemRequestClosingDate) validateCreateCatalogItemRequestClosingDateEnum(path, location string, value CreateCatalogItemRequestClosingDate) error {
	if err := validate.EnumCase(path, location, value, createCatalogItemRequestClosingDateEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this create catalog item request closing date
func (m CreateCatalogItemRequestClosingDate) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateCreateCatalogItemRequestClosingDateEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this create catalog item request closing date based on context it is used
func (m CreateCatalogItemRequestClosingDate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
