// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// OrderDirection 順序
//
// - DIRECTION_ASCENDING: 昇順
//   - DIRECTION_DESCENDING: 降順
//
// swagger:model OrderDirection
type OrderDirection string

func NewOrderDirection(value OrderDirection) *OrderDirection {
	return &value
}

// Pointer returns a pointer to a freshly-allocated OrderDirection.
func (m OrderDirection) Pointer() *OrderDirection {
	return &m
}

const (

	// OrderDirectionDIRECTIONASCENDING captures enum value "DIRECTION_ASCENDING"
	OrderDirectionDIRECTIONASCENDING OrderDirection = "DIRECTION_ASCENDING"

	// OrderDirectionDIRECTIONDESCENDING captures enum value "DIRECTION_DESCENDING"
	OrderDirectionDIRECTIONDESCENDING OrderDirection = "DIRECTION_DESCENDING"
)

// for schema
var orderDirectionEnum []interface{}

func init() {
	var res []OrderDirection
	if err := json.Unmarshal([]byte(`["DIRECTION_ASCENDING","DIRECTION_DESCENDING"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		orderDirectionEnum = append(orderDirectionEnum, v)
	}
}

func (m OrderDirection) validateOrderDirectionEnum(path, location string, value OrderDirection) error {
	if err := validate.EnumCase(path, location, value, orderDirectionEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this order direction
func (m OrderDirection) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateOrderDirectionEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this order direction based on context it is used
func (m OrderDirection) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
