// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ProtobufNullValue `NullValue` is a singleton enumeration to represent the null value for the
// `Value` type union.
//
//	The JSON representation for `NullValue` is JSON `null`.
//
//	- NULL_VALUE: Null value.
//
// swagger:model protobufNullValue
type ProtobufNullValue string

// Validate validates this protobuf null value
func (m ProtobufNullValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this protobuf null value based on context it is used
func (m ProtobufNullValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
