// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Publicv1Customer 顧客
//
// swagger:model publicv1Customer
type Publicv1Customer struct {

	// 顧客ID
	ID string `json:"id,omitempty"`

	// 顧客名（更新可）
	Name string `json:"name,omitempty"`

	// 顧客管理ID（更新時、顧客IDの代わりに指定可）
	OptionalID string `json:"optionalId,omitempty"`
}

// Validate validates this publicv1 customer
func (m *Publicv1Customer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this publicv1 customer based on context it is used
func (m *Publicv1Customer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Publicv1Customer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Publicv1Customer) UnmarshalBinary(b []byte) error {
	var res Publicv1Customer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
