// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Publicv1CustomerStaffName 名前
//
// swagger:model publicv1CustomerStaffName
type Publicv1CustomerStaffName struct {

	// 顧客担当者の名
	FirstName string `json:"firstName,omitempty"`

	// 顧客担当者の姓
	LastName string `json:"lastName,omitempty"`
}

// Validate validates this publicv1 customer staff name
func (m *Publicv1CustomerStaffName) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this publicv1 customer staff name based on context it is used
func (m *Publicv1CustomerStaffName) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Publicv1CustomerStaffName) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Publicv1CustomerStaffName) UnmarshalBinary(b []byte) error {
	var res Publicv1CustomerStaffName
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
