// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SearchBillingsRequestClause フィルター項目
// example:
//
//	{ "status": { "eq": "STATUS_UNBILLED" }}
//
// swagger:model SearchBillingsRequestClause
type SearchBillingsRequestClause struct {

	// billing date
	BillingDate *ClauseBillingDate `json:"billingDate,omitempty"`

	// status
	Status *SearchBillingsRequestClauseStatus `json:"status,omitempty"`
}

// Validate validates this search billings request clause
func (m *SearchBillingsRequestClause) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBillingDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SearchBillingsRequestClause) validateBillingDate(formats strfmt.Registry) error {
	if swag.IsZero(m.BillingDate) { // not required
		return nil
	}

	if m.BillingDate != nil {
		if err := m.BillingDate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("billingDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("billingDate")
			}
			return err
		}
	}

	return nil
}

func (m *SearchBillingsRequestClause) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this search billings request clause based on the context it is used
func (m *SearchBillingsRequestClause) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBillingDate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SearchBillingsRequestClause) contextValidateBillingDate(ctx context.Context, formats strfmt.Registry) error {

	if m.BillingDate != nil {

		if swag.IsZero(m.BillingDate) { // not required
			return nil
		}

		if err := m.BillingDate.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("billingDate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("billingDate")
			}
			return err
		}
	}

	return nil
}

func (m *SearchBillingsRequestClause) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	if m.Status != nil {

		if swag.IsZero(m.Status) { // not required
			return nil
		}

		if err := m.Status.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SearchBillingsRequestClause) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SearchBillingsRequestClause) UnmarshalBinary(b []byte) error {
	var res SearchBillingsRequestClause
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
