// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V1BillingStatus v1 billing status
//
// swagger:model v1BillingStatus
type V1BillingStatus string

func NewV1BillingStatus(value V1BillingStatus) *V1BillingStatus {
	return &value
}

// Pointer returns a pointer to a freshly-allocated V1BillingStatus.
func (m V1BillingStatus) Pointer() *V1BillingStatus {
	return &m
}

const (

	// V1BillingStatusSTATUSHOLDINVOICECREATION captures enum value "STATUS_HOLD_INVOICE_CREATION"
	V1BillingStatusSTATUSHOLDINVOICECREATION V1BillingStatus = "STATUS_HOLD_INVOICE_CREATION"

	// V1BillingStatusSTATUSUNBILLED captures enum value "STATUS_UNBILLED"
	V1BillingStatusSTATUSUNBILLED V1BillingStatus = "STATUS_UNBILLED"

	// V1BillingStatusSTATUSPOSTED captures enum value "STATUS_POSTED"
	V1BillingStatusSTATUSPOSTED V1BillingStatus = "STATUS_POSTED"

	// V1BillingStatusSTATUSPARTIALLYPAID captures enum value "STATUS_PARTIALLY_PAID"
	V1BillingStatusSTATUSPARTIALLYPAID V1BillingStatus = "STATUS_PARTIALLY_PAID"

	// V1BillingStatusSTATUSPAID captures enum value "STATUS_PAID"
	V1BillingStatusSTATUSPAID V1BillingStatus = "STATUS_PAID"

	// V1BillingStatusSTATUSPAYMENTEXCLUDED captures enum value "STATUS_PAYMENT_EXCLUDED"
	V1BillingStatusSTATUSPAYMENTEXCLUDED V1BillingStatus = "STATUS_PAYMENT_EXCLUDED"

	// V1BillingStatusSTATUSPAYMENTDUE captures enum value "STATUS_PAYMENT_DUE"
	V1BillingStatusSTATUSPAYMENTDUE V1BillingStatus = "STATUS_PAYMENT_DUE"

	// V1BillingStatusSTATUSPAYMENTUNNECESSARY captures enum value "STATUS_PAYMENT_UNNECESSARY"
	V1BillingStatusSTATUSPAYMENTUNNECESSARY V1BillingStatus = "STATUS_PAYMENT_UNNECESSARY"

	// V1BillingStatusSTATUSPARTIALLYUNPAID captures enum value "STATUS_PARTIALLY_UNPAID"
	V1BillingStatusSTATUSPARTIALLYUNPAID V1BillingStatus = "STATUS_PARTIALLY_UNPAID"

	// V1BillingStatusSTATUSPAYMENTREFUNDED captures enum value "STATUS_PAYMENT_REFUNDED"
	V1BillingStatusSTATUSPAYMENTREFUNDED V1BillingStatus = "STATUS_PAYMENT_REFUNDED"

	// V1BillingStatusSTATUSPAIDWITHCARD captures enum value "STATUS_PAID_WITH_CARD"
	V1BillingStatusSTATUSPAIDWITHCARD V1BillingStatus = "STATUS_PAID_WITH_CARD"

	// V1BillingStatusSTATUSINVOICECREATED captures enum value "STATUS_INVOICE_CREATED"
	V1BillingStatusSTATUSINVOICECREATED V1BillingStatus = "STATUS_INVOICE_CREATED"

	// V1BillingStatusSTATUSINVOICEDELETED captures enum value "STATUS_INVOICE_DELETED"
	V1BillingStatusSTATUSINVOICEDELETED V1BillingStatus = "STATUS_INVOICE_DELETED"

	// V1BillingStatusSTATUSINVALIDATED captures enum value "STATUS_INVALIDATED"
	V1BillingStatusSTATUSINVALIDATED V1BillingStatus = "STATUS_INVALIDATED"
)

// for schema
var v1BillingStatusEnum []interface{}

func init() {
	var res []V1BillingStatus
	if err := json.Unmarshal([]byte(`["STATUS_HOLD_INVOICE_CREATION","STATUS_UNBILLED","STATUS_POSTED","STATUS_PARTIALLY_PAID","STATUS_PAID","STATUS_PAYMENT_EXCLUDED","STATUS_PAYMENT_DUE","STATUS_PAYMENT_UNNECESSARY","STATUS_PARTIALLY_UNPAID","STATUS_PAYMENT_REFUNDED","STATUS_PAID_WITH_CARD","STATUS_INVOICE_CREATED","STATUS_INVOICE_DELETED","STATUS_INVALIDATED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1BillingStatusEnum = append(v1BillingStatusEnum, v)
	}
}

func (m V1BillingStatus) validateV1BillingStatusEnum(path, location string, value V1BillingStatus) error {
	if err := validate.EnumCase(path, location, value, v1BillingStatusEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this v1 billing status
func (m V1BillingStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV1BillingStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this v1 billing status based on context it is used
func (m V1BillingStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
