// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1BillingItem v1 billing item
//
// swagger:model v1BillingItem
type V1BillingItem struct {

	// 請求項目ID
	ID string `json:"id,omitempty"`

	// 請求項目名
	Name string `json:"name,omitempty"`

	// 数量
	Quantity string `json:"quantity,omitempty"`

	// 小計
	Subtotal float64 `json:"subtotal,omitempty"`

	// 税率
	TaxPercentage int32 `json:"taxPercentage,omitempty"`

	// 単価
	UnitPrice float64 `json:"unitPrice,omitempty"`
}

// Validate validates this v1 billing item
func (m *V1BillingItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 billing item based on context it is used
func (m *V1BillingItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1BillingItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1BillingItem) UnmarshalBinary(b []byte) error {
	var res V1BillingItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
