// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V1BillingCustomerStaffAddressCountry 国
//
// swagger:model v1BillingCustomerStaffAddressCountry
type V1BillingCustomerStaffAddressCountry string

func NewV1BillingCustomerStaffAddressCountry(value V1BillingCustomerStaffAddressCountry) *V1BillingCustomerStaffAddressCountry {
	return &value
}

// Pointer returns a pointer to a freshly-allocated V1BillingCustomerStaffAddressCountry.
func (m V1BillingCustomerStaffAddressCountry) Pointer() *V1BillingCustomerStaffAddressCountry {
	return &m
}

const (

	// V1BillingCustomerStaffAddressCountryCOUNTRYJP captures enum value "COUNTRY_JP"
	V1BillingCustomerStaffAddressCountryCOUNTRYJP V1BillingCustomerStaffAddressCountry = "COUNTRY_JP"
)

// for schema
var v1BillingCustomerStaffAddressCountryEnum []interface{}

func init() {
	var res []V1BillingCustomerStaffAddressCountry
	if err := json.Unmarshal([]byte(`["COUNTRY_JP"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1BillingCustomerStaffAddressCountryEnum = append(v1BillingCustomerStaffAddressCountryEnum, v)
	}
}

func (m V1BillingCustomerStaffAddressCountry) validateV1BillingCustomerStaffAddressCountryEnum(path, location string, value V1BillingCustomerStaffAddressCountry) error {
	if err := validate.EnumCase(path, location, value, v1BillingCustomerStaffAddressCountryEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this v1 billing customer staff address country
func (m V1BillingCustomerStaffAddressCountry) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV1BillingCustomerStaffAddressCountryEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this v1 billing customer staff address country based on context it is used
func (m V1BillingCustomerStaffAddressCountry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
