// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V1BillingCustomerStaffAddressPrefecture 都道府県
//
// swagger:model v1BillingCustomerStaffAddressPrefecture
type V1BillingCustomerStaffAddressPrefecture string

func NewV1BillingCustomerStaffAddressPrefecture(value V1BillingCustomerStaffAddressPrefecture) *V1BillingCustomerStaffAddressPrefecture {
	return &value
}

// Pointer returns a pointer to a freshly-allocated V1BillingCustomerStaffAddressPrefecture.
func (m V1BillingCustomerStaffAddressPrefecture) Pointer() *V1BillingCustomerStaffAddressPrefecture {
	return &m
}

const (

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREHOKKAIDO captures enum value "PREFECTURE_HOKKAIDO"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREHOKKAIDO V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_HOKKAIDO"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREAOMORI captures enum value "PREFECTURE_AOMORI"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREAOMORI V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_AOMORI"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREIWATE captures enum value "PREFECTURE_IWATE"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREIWATE V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_IWATE"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREMIYAGI captures enum value "PREFECTURE_MIYAGI"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREMIYAGI V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_MIYAGI"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREAKITA captures enum value "PREFECTURE_AKITA"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREAKITA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_AKITA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREYAMAGATA captures enum value "PREFECTURE_YAMAGATA"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREYAMAGATA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_YAMAGATA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREFUKUSHIMA captures enum value "PREFECTURE_FUKUSHIMA"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREFUKUSHIMA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_FUKUSHIMA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREIBARAKI captures enum value "PREFECTURE_IBARAKI"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREIBARAKI V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_IBARAKI"

	// V1BillingCustomerStaffAddressPrefecturePREFECTURETOCHIGI captures enum value "PREFECTURE_TOCHIGI"
	V1BillingCustomerStaffAddressPrefecturePREFECTURETOCHIGI V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_TOCHIGI"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREGUNMA captures enum value "PREFECTURE_GUNMA"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREGUNMA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_GUNMA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTURESAITAMA captures enum value "PREFECTURE_SAITAMA"
	V1BillingCustomerStaffAddressPrefecturePREFECTURESAITAMA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_SAITAMA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTURECHIBA captures enum value "PREFECTURE_CHIBA"
	V1BillingCustomerStaffAddressPrefecturePREFECTURECHIBA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_CHIBA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTURETOKYO captures enum value "PREFECTURE_TOKYO"
	V1BillingCustomerStaffAddressPrefecturePREFECTURETOKYO V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_TOKYO"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREKANAGAWA captures enum value "PREFECTURE_KANAGAWA"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREKANAGAWA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_KANAGAWA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTURENIIGATA captures enum value "PREFECTURE_NIIGATA"
	V1BillingCustomerStaffAddressPrefecturePREFECTURENIIGATA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_NIIGATA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTURETOYAMA captures enum value "PREFECTURE_TOYAMA"
	V1BillingCustomerStaffAddressPrefecturePREFECTURETOYAMA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_TOYAMA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREISHIKAWA captures enum value "PREFECTURE_ISHIKAWA"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREISHIKAWA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_ISHIKAWA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREFUKUI captures enum value "PREFECTURE_FUKUI"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREFUKUI V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_FUKUI"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREYAMANASHI captures enum value "PREFECTURE_YAMANASHI"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREYAMANASHI V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_YAMANASHI"

	// V1BillingCustomerStaffAddressPrefecturePREFECTURENAGANO captures enum value "PREFECTURE_NAGANO"
	V1BillingCustomerStaffAddressPrefecturePREFECTURENAGANO V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_NAGANO"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREGIFU captures enum value "PREFECTURE_GIFU"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREGIFU V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_GIFU"

	// V1BillingCustomerStaffAddressPrefecturePREFECTURESHIZUOKA captures enum value "PREFECTURE_SHIZUOKA"
	V1BillingCustomerStaffAddressPrefecturePREFECTURESHIZUOKA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_SHIZUOKA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREAICHI captures enum value "PREFECTURE_AICHI"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREAICHI V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_AICHI"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREMIE captures enum value "PREFECTURE_MIE"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREMIE V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_MIE"

	// V1BillingCustomerStaffAddressPrefecturePREFECTURESHIGA captures enum value "PREFECTURE_SHIGA"
	V1BillingCustomerStaffAddressPrefecturePREFECTURESHIGA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_SHIGA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREKYOTO captures enum value "PREFECTURE_KYOTO"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREKYOTO V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_KYOTO"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREOSAKA captures enum value "PREFECTURE_OSAKA"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREOSAKA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_OSAKA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREHYOGO captures enum value "PREFECTURE_HYOGO"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREHYOGO V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_HYOGO"

	// V1BillingCustomerStaffAddressPrefecturePREFECTURENARA captures enum value "PREFECTURE_NARA"
	V1BillingCustomerStaffAddressPrefecturePREFECTURENARA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_NARA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREWAKAYAMA captures enum value "PREFECTURE_WAKAYAMA"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREWAKAYAMA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_WAKAYAMA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTURETOTTORI captures enum value "PREFECTURE_TOTTORI"
	V1BillingCustomerStaffAddressPrefecturePREFECTURETOTTORI V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_TOTTORI"

	// V1BillingCustomerStaffAddressPrefecturePREFECTURESHIMANE captures enum value "PREFECTURE_SHIMANE"
	V1BillingCustomerStaffAddressPrefecturePREFECTURESHIMANE V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_SHIMANE"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREOKAYAMA captures enum value "PREFECTURE_OKAYAMA"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREOKAYAMA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_OKAYAMA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREHIROSHIMA captures enum value "PREFECTURE_HIROSHIMA"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREHIROSHIMA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_HIROSHIMA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREYAMAGUCHI captures enum value "PREFECTURE_YAMAGUCHI"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREYAMAGUCHI V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_YAMAGUCHI"

	// V1BillingCustomerStaffAddressPrefecturePREFECTURETOKUSHIMA captures enum value "PREFECTURE_TOKUSHIMA"
	V1BillingCustomerStaffAddressPrefecturePREFECTURETOKUSHIMA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_TOKUSHIMA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREKAGAWA captures enum value "PREFECTURE_KAGAWA"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREKAGAWA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_KAGAWA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREEHIME captures enum value "PREFECTURE_EHIME"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREEHIME V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_EHIME"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREKOCHI captures enum value "PREFECTURE_KOCHI"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREKOCHI V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_KOCHI"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREFUKUOKA captures enum value "PREFECTURE_FUKUOKA"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREFUKUOKA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_FUKUOKA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTURESAGA captures enum value "PREFECTURE_SAGA"
	V1BillingCustomerStaffAddressPrefecturePREFECTURESAGA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_SAGA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTURENAGASAKI captures enum value "PREFECTURE_NAGASAKI"
	V1BillingCustomerStaffAddressPrefecturePREFECTURENAGASAKI V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_NAGASAKI"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREKUMAMOTO captures enum value "PREFECTURE_KUMAMOTO"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREKUMAMOTO V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_KUMAMOTO"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREOITA captures enum value "PREFECTURE_OITA"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREOITA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_OITA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREMIYAZAKI captures enum value "PREFECTURE_MIYAZAKI"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREMIYAZAKI V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_MIYAZAKI"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREKAGOSHIMA captures enum value "PREFECTURE_KAGOSHIMA"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREKAGOSHIMA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_KAGOSHIMA"

	// V1BillingCustomerStaffAddressPrefecturePREFECTUREOKINAWA captures enum value "PREFECTURE_OKINAWA"
	V1BillingCustomerStaffAddressPrefecturePREFECTUREOKINAWA V1BillingCustomerStaffAddressPrefecture = "PREFECTURE_OKINAWA"
)

// for schema
var v1BillingCustomerStaffAddressPrefectureEnum []interface{}

func init() {
	var res []V1BillingCustomerStaffAddressPrefecture
	if err := json.Unmarshal([]byte(`["PREFECTURE_HOKKAIDO","PREFECTURE_AOMORI","PREFECTURE_IWATE","PREFECTURE_MIYAGI","PREFECTURE_AKITA","PREFECTURE_YAMAGATA","PREFECTURE_FUKUSHIMA","PREFECTURE_IBARAKI","PREFECTURE_TOCHIGI","PREFECTURE_GUNMA","PREFECTURE_SAITAMA","PREFECTURE_CHIBA","PREFECTURE_TOKYO","PREFECTURE_KANAGAWA","PREFECTURE_NIIGATA","PREFECTURE_TOYAMA","PREFECTURE_ISHIKAWA","PREFECTURE_FUKUI","PREFECTURE_YAMANASHI","PREFECTURE_NAGANO","PREFECTURE_GIFU","PREFECTURE_SHIZUOKA","PREFECTURE_AICHI","PREFECTURE_MIE","PREFECTURE_SHIGA","PREFECTURE_KYOTO","PREFECTURE_OSAKA","PREFECTURE_HYOGO","PREFECTURE_NARA","PREFECTURE_WAKAYAMA","PREFECTURE_TOTTORI","PREFECTURE_SHIMANE","PREFECTURE_OKAYAMA","PREFECTURE_HIROSHIMA","PREFECTURE_YAMAGUCHI","PREFECTURE_TOKUSHIMA","PREFECTURE_KAGAWA","PREFECTURE_EHIME","PREFECTURE_KOCHI","PREFECTURE_FUKUOKA","PREFECTURE_SAGA","PREFECTURE_NAGASAKI","PREFECTURE_KUMAMOTO","PREFECTURE_OITA","PREFECTURE_MIYAZAKI","PREFECTURE_KAGOSHIMA","PREFECTURE_OKINAWA"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1BillingCustomerStaffAddressPrefectureEnum = append(v1BillingCustomerStaffAddressPrefectureEnum, v)
	}
}

func (m V1BillingCustomerStaffAddressPrefecture) validateV1BillingCustomerStaffAddressPrefectureEnum(path, location string, value V1BillingCustomerStaffAddressPrefecture) error {
	if err := validate.EnumCase(path, location, value, v1BillingCustomerStaffAddressPrefectureEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this v1 billing customer staff address prefecture
func (m V1BillingCustomerStaffAddressPrefecture) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV1BillingCustomerStaffAddressPrefectureEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this v1 billing customer staff address prefecture based on context it is used
func (m V1BillingCustomerStaffAddressPrefecture) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
