// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V1CreateCustomerStaffRequestAddressPrefecture 都道府県
//
// swagger:model v1CreateCustomerStaffRequestAddressPrefecture
type V1CreateCustomerStaffRequestAddressPrefecture string

func NewV1CreateCustomerStaffRequestAddressPrefecture(value V1CreateCustomerStaffRequestAddressPrefecture) *V1CreateCustomerStaffRequestAddressPrefecture {
	return &value
}

// Pointer returns a pointer to a freshly-allocated V1CreateCustomerStaffRequestAddressPrefecture.
func (m V1CreateCustomerStaffRequestAddressPrefecture) Pointer() *V1CreateCustomerStaffRequestAddressPrefecture {
	return &m
}

const (

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREHOKKAIDO captures enum value "PREFECTURE_HOKKAIDO"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREHOKKAIDO V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_HOKKAIDO"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREAOMORI captures enum value "PREFECTURE_AOMORI"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREAOMORI V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_AOMORI"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREIWATE captures enum value "PREFECTURE_IWATE"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREIWATE V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_IWATE"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREMIYAGI captures enum value "PREFECTURE_MIYAGI"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREMIYAGI V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_MIYAGI"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREAKITA captures enum value "PREFECTURE_AKITA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREAKITA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_AKITA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREYAMAGATA captures enum value "PREFECTURE_YAMAGATA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREYAMAGATA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_YAMAGATA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREFUKUSHIMA captures enum value "PREFECTURE_FUKUSHIMA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREFUKUSHIMA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_FUKUSHIMA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREIBARAKI captures enum value "PREFECTURE_IBARAKI"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREIBARAKI V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_IBARAKI"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTURETOCHIGI captures enum value "PREFECTURE_TOCHIGI"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTURETOCHIGI V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_TOCHIGI"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREGUNMA captures enum value "PREFECTURE_GUNMA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREGUNMA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_GUNMA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTURESAITAMA captures enum value "PREFECTURE_SAITAMA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTURESAITAMA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_SAITAMA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTURECHIBA captures enum value "PREFECTURE_CHIBA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTURECHIBA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_CHIBA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTURETOKYO captures enum value "PREFECTURE_TOKYO"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTURETOKYO V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_TOKYO"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREKANAGAWA captures enum value "PREFECTURE_KANAGAWA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREKANAGAWA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_KANAGAWA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTURENIIGATA captures enum value "PREFECTURE_NIIGATA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTURENIIGATA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_NIIGATA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTURETOYAMA captures enum value "PREFECTURE_TOYAMA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTURETOYAMA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_TOYAMA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREISHIKAWA captures enum value "PREFECTURE_ISHIKAWA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREISHIKAWA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_ISHIKAWA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREFUKUI captures enum value "PREFECTURE_FUKUI"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREFUKUI V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_FUKUI"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREYAMANASHI captures enum value "PREFECTURE_YAMANASHI"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREYAMANASHI V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_YAMANASHI"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTURENAGANO captures enum value "PREFECTURE_NAGANO"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTURENAGANO V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_NAGANO"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREGIFU captures enum value "PREFECTURE_GIFU"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREGIFU V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_GIFU"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTURESHIZUOKA captures enum value "PREFECTURE_SHIZUOKA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTURESHIZUOKA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_SHIZUOKA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREAICHI captures enum value "PREFECTURE_AICHI"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREAICHI V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_AICHI"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREMIE captures enum value "PREFECTURE_MIE"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREMIE V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_MIE"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTURESHIGA captures enum value "PREFECTURE_SHIGA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTURESHIGA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_SHIGA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREKYOTO captures enum value "PREFECTURE_KYOTO"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREKYOTO V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_KYOTO"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREOSAKA captures enum value "PREFECTURE_OSAKA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREOSAKA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_OSAKA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREHYOGO captures enum value "PREFECTURE_HYOGO"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREHYOGO V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_HYOGO"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTURENARA captures enum value "PREFECTURE_NARA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTURENARA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_NARA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREWAKAYAMA captures enum value "PREFECTURE_WAKAYAMA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREWAKAYAMA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_WAKAYAMA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTURETOTTORI captures enum value "PREFECTURE_TOTTORI"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTURETOTTORI V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_TOTTORI"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTURESHIMANE captures enum value "PREFECTURE_SHIMANE"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTURESHIMANE V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_SHIMANE"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREOKAYAMA captures enum value "PREFECTURE_OKAYAMA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREOKAYAMA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_OKAYAMA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREHIROSHIMA captures enum value "PREFECTURE_HIROSHIMA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREHIROSHIMA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_HIROSHIMA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREYAMAGUCHI captures enum value "PREFECTURE_YAMAGUCHI"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREYAMAGUCHI V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_YAMAGUCHI"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTURETOKUSHIMA captures enum value "PREFECTURE_TOKUSHIMA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTURETOKUSHIMA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_TOKUSHIMA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREKAGAWA captures enum value "PREFECTURE_KAGAWA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREKAGAWA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_KAGAWA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREEHIME captures enum value "PREFECTURE_EHIME"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREEHIME V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_EHIME"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREKOCHI captures enum value "PREFECTURE_KOCHI"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREKOCHI V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_KOCHI"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREFUKUOKA captures enum value "PREFECTURE_FUKUOKA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREFUKUOKA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_FUKUOKA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTURESAGA captures enum value "PREFECTURE_SAGA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTURESAGA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_SAGA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTURENAGASAKI captures enum value "PREFECTURE_NAGASAKI"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTURENAGASAKI V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_NAGASAKI"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREKUMAMOTO captures enum value "PREFECTURE_KUMAMOTO"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREKUMAMOTO V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_KUMAMOTO"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREOITA captures enum value "PREFECTURE_OITA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREOITA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_OITA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREMIYAZAKI captures enum value "PREFECTURE_MIYAZAKI"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREMIYAZAKI V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_MIYAZAKI"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREKAGOSHIMA captures enum value "PREFECTURE_KAGOSHIMA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREKAGOSHIMA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_KAGOSHIMA"

	// V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREOKINAWA captures enum value "PREFECTURE_OKINAWA"
	V1CreateCustomerStaffRequestAddressPrefecturePREFECTUREOKINAWA V1CreateCustomerStaffRequestAddressPrefecture = "PREFECTURE_OKINAWA"
)

// for schema
var v1CreateCustomerStaffRequestAddressPrefectureEnum []interface{}

func init() {
	var res []V1CreateCustomerStaffRequestAddressPrefecture
	if err := json.Unmarshal([]byte(`["PREFECTURE_HOKKAIDO","PREFECTURE_AOMORI","PREFECTURE_IWATE","PREFECTURE_MIYAGI","PREFECTURE_AKITA","PREFECTURE_YAMAGATA","PREFECTURE_FUKUSHIMA","PREFECTURE_IBARAKI","PREFECTURE_TOCHIGI","PREFECTURE_GUNMA","PREFECTURE_SAITAMA","PREFECTURE_CHIBA","PREFECTURE_TOKYO","PREFECTURE_KANAGAWA","PREFECTURE_NIIGATA","PREFECTURE_TOYAMA","PREFECTURE_ISHIKAWA","PREFECTURE_FUKUI","PREFECTURE_YAMANASHI","PREFECTURE_NAGANO","PREFECTURE_GIFU","PREFECTURE_SHIZUOKA","PREFECTURE_AICHI","PREFECTURE_MIE","PREFECTURE_SHIGA","PREFECTURE_KYOTO","PREFECTURE_OSAKA","PREFECTURE_HYOGO","PREFECTURE_NARA","PREFECTURE_WAKAYAMA","PREFECTURE_TOTTORI","PREFECTURE_SHIMANE","PREFECTURE_OKAYAMA","PREFECTURE_HIROSHIMA","PREFECTURE_YAMAGUCHI","PREFECTURE_TOKUSHIMA","PREFECTURE_KAGAWA","PREFECTURE_EHIME","PREFECTURE_KOCHI","PREFECTURE_FUKUOKA","PREFECTURE_SAGA","PREFECTURE_NAGASAKI","PREFECTURE_KUMAMOTO","PREFECTURE_OITA","PREFECTURE_MIYAZAKI","PREFECTURE_KAGOSHIMA","PREFECTURE_OKINAWA"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1CreateCustomerStaffRequestAddressPrefectureEnum = append(v1CreateCustomerStaffRequestAddressPrefectureEnum, v)
	}
}

func (m V1CreateCustomerStaffRequestAddressPrefecture) validateV1CreateCustomerStaffRequestAddressPrefectureEnum(path, location string, value V1CreateCustomerStaffRequestAddressPrefecture) error {
	if err := validate.EnumCase(path, location, value, v1CreateCustomerStaffRequestAddressPrefectureEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this v1 create customer staff request address prefecture
func (m V1CreateCustomerStaffRequestAddressPrefecture) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV1CreateCustomerStaffRequestAddressPrefectureEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this v1 create customer staff request address prefecture based on context it is used
func (m V1CreateCustomerStaffRequestAddressPrefecture) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
