// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1CreateCustomerStaffResponse 顧客担当者作成のレスポンス
//
// swagger:model v1CreateCustomerStaffResponse
type V1CreateCustomerStaffResponse struct {

	// 顧客担当者
	CustomerStaff *Publicv1CustomerStaff `json:"customerStaff,omitempty"`
}

// Validate validates this v1 create customer staff response
func (m *V1CreateCustomerStaffResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCustomerStaff(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1CreateCustomerStaffResponse) validateCustomerStaff(formats strfmt.Registry) error {
	if swag.IsZero(m.CustomerStaff) { // not required
		return nil
	}

	if m.CustomerStaff != nil {
		if err := m.CustomerStaff.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("customerStaff")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("customerStaff")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 create customer staff response based on the context it is used
func (m *V1CreateCustomerStaffResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCustomerStaff(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1CreateCustomerStaffResponse) contextValidateCustomerStaff(ctx context.Context, formats strfmt.Registry) error {

	if m.CustomerStaff != nil {
		if err := m.CustomerStaff.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("customerStaff")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("customerStaff")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1CreateCustomerStaffResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1CreateCustomerStaffResponse) UnmarshalBinary(b []byte) error {
	var res V1CreateCustomerStaffResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
