// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1CreateUsageUnitResponse 使用量単位の作成レスポンス
//
// swagger:model v1CreateUsageUnitResponse
type V1CreateUsageUnitResponse struct {

	// usage unit
	UsageUnit *V1UsageUnit `json:"usageUnit,omitempty"`
}

// Validate validates this v1 create usage unit response
func (m *V1CreateUsageUnitResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUsageUnit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1CreateUsageUnitResponse) validateUsageUnit(formats strfmt.Registry) error {
	if swag.IsZero(m.UsageUnit) { // not required
		return nil
	}

	if m.UsageUnit != nil {
		if err := m.UsageUnit.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("usageUnit")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("usageUnit")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 create usage unit response based on the context it is used
func (m *V1CreateUsageUnitResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateUsageUnit(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1CreateUsageUnitResponse) contextValidateUsageUnit(ctx context.Context, formats strfmt.Registry) error {

	if m.UsageUnit != nil {
		if err := m.UsageUnit.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("usageUnit")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("usageUnit")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1CreateUsageUnitResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1CreateUsageUnitResponse) UnmarshalBinary(b []byte) error {
	var res V1CreateUsageUnitResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
