// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1CreateProductRequest プロダクト作成のリクエスト
//
// swagger:model v1CreateProductRequest
type V1CreateProductRequest struct {

	// プロダクト概要
	Description string `json:"description,omitempty"`

	// プロダクト名
	Name string `json:"name,omitempty"`

	// プロダクト管理ID
	OptionalID string `json:"optionalId,omitempty"`
}

// Validate validates this v1 create product request
func (m *V1CreateProductRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 create product request based on context it is used
func (m *V1CreateProductRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1CreateProductRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1CreateProductRequest) UnmarshalBinary(b []byte) error {
	var res V1CreateProductRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
