// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1CreateCatalogItemResponse カタログアイテム作成のレスポンス
//
// swagger:model v1CreateCatalogItemResponse
type V1CreateCatalogItemResponse struct {

	// catalog item
	CatalogItem *V1CatalogItem `json:"catalogItem,omitempty"`
}

// Validate validates this v1 create catalog item response
func (m *V1CreateCatalogItemResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCatalogItem(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1CreateCatalogItemResponse) validateCatalogItem(formats strfmt.Registry) error {
	if swag.IsZero(m.CatalogItem) { // not required
		return nil
	}

	if m.CatalogItem != nil {
		if err := m.CatalogItem.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("catalogItem")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("catalogItem")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 create catalog item response based on the context it is used
func (m *V1CreateCatalogItemResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCatalogItem(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1CreateCatalogItemResponse) contextValidateCatalogItem(ctx context.Context, formats strfmt.Registry) error {

	if m.CatalogItem != nil {
		if err := m.CatalogItem.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("catalogItem")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("catalogItem")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1CreateCatalogItemResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1CreateCatalogItemResponse) UnmarshalBinary(b []byte) error {
	var res V1CreateCatalogItemResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
