// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1DeleteCustomFieldMasterResponse カスタムフィールドマスター削除のレスポンス
//
// swagger:model v1DeleteCustomFieldMasterResponse
type V1DeleteCustomFieldMasterResponse interface{}
