// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1ListExpectedBillingsByContractResponse 契約に紐づく請求予定一覧取得のレスポンス
//
// swagger:model v1ListExpectedBillingsByContractResponse
type V1ListExpectedBillingsByContractResponse struct {

	// 請求予定
	ExpectedBillings []*V1ExpectedBilling `json:"expectedBillings"`

	// 次の一覧取得に使用するトークン
	NextPageToken string `json:"nextPageToken,omitempty"`
}

// Validate validates this v1 list expected billings by contract response
func (m *V1ListExpectedBillingsByContractResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpectedBillings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1ListExpectedBillingsByContractResponse) validateExpectedBillings(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpectedBillings) { // not required
		return nil
	}

	for i := 0; i < len(m.ExpectedBillings); i++ {
		if swag.IsZero(m.ExpectedBillings[i]) { // not required
			continue
		}

		if m.ExpectedBillings[i] != nil {
			if err := m.ExpectedBillings[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("expectedBillings" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("expectedBillings" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v1 list expected billings by contract response based on the context it is used
func (m *V1ListExpectedBillingsByContractResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateExpectedBillings(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1ListExpectedBillingsByContractResponse) contextValidateExpectedBillings(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ExpectedBillings); i++ {

		if m.ExpectedBillings[i] != nil {
			if err := m.ExpectedBillings[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("expectedBillings" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("expectedBillings" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1ListExpectedBillingsByContractResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1ListExpectedBillingsByContractResponse) UnmarshalBinary(b []byte) error {
	var res V1ListExpectedBillingsByContractResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
