// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// V1ListAmendmentsRequestOrderField 対象
//
// - FIELD_ID: ID
//   - FIELD_EXECUTE_DATE: 改定実行日
//
// swagger:model v1ListAmendmentsRequestOrderField
type V1ListAmendmentsRequestOrderField string

func NewV1ListAmendmentsRequestOrderField(value V1ListAmendmentsRequestOrderField) *V1ListAmendmentsRequestOrderField {
	return &value
}

// Pointer returns a pointer to a freshly-allocated V1ListAmendmentsRequestOrderField.
func (m V1ListAmendmentsRequestOrderField) Pointer() *V1ListAmendmentsRequestOrderField {
	return &m
}

const (

	// V1ListAmendmentsRequestOrderFieldFIELDID captures enum value "FIELD_ID"
	V1ListAmendmentsRequestOrderFieldFIELDID V1ListAmendmentsRequestOrderField = "FIELD_ID"

	// V1ListAmendmentsRequestOrderFieldFIELDEXECUTEDATE captures enum value "FIELD_EXECUTE_DATE"
	V1ListAmendmentsRequestOrderFieldFIELDEXECUTEDATE V1ListAmendmentsRequestOrderField = "FIELD_EXECUTE_DATE"
)

// for schema
var v1ListAmendmentsRequestOrderFieldEnum []interface{}

func init() {
	var res []V1ListAmendmentsRequestOrderField
	if err := json.Unmarshal([]byte(`["FIELD_ID","FIELD_EXECUTE_DATE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1ListAmendmentsRequestOrderFieldEnum = append(v1ListAmendmentsRequestOrderFieldEnum, v)
	}
}

func (m V1ListAmendmentsRequestOrderField) validateV1ListAmendmentsRequestOrderFieldEnum(path, location string, value V1ListAmendmentsRequestOrderField) error {
	if err := validate.EnumCase(path, location, value, v1ListAmendmentsRequestOrderFieldEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this v1 list amendments request order field
func (m V1ListAmendmentsRequestOrderField) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateV1ListAmendmentsRequestOrderFieldEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this v1 list amendments request order field based on context it is used
func (m V1ListAmendmentsRequestOrderField) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
