// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1Product プロダクト
//
// swagger:model v1Product
type V1Product struct {

	// プロダクト概要
	Description string `json:"description,omitempty"`

	// プロダクトID
	ID string `json:"id,omitempty"`

	// プロダクト名
	Name string `json:"name,omitempty"`

	// プロダクト管理ID
	OptionalID string `json:"optionalId,omitempty"`
}

// Validate validates this v1 product
func (m *V1Product) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 product based on context it is used
func (m *V1Product) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1Product) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Product) UnmarshalBinary(b []byte) error {
	var res V1Product
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
