// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1Provider プロバイダー
//
// swagger:model v1Provider
type V1Provider struct {

	// 住所
	Address *V1ProviderAddress `json:"address,omitempty"`

	// メールアドレス
	EmailAddress string `json:"emailAddress,omitempty"`

	// 企業名
	Name string `json:"name,omitempty"`

	// 電話番号
	PhoneNumber string `json:"phoneNumber,omitempty"`

	// 代表氏名
	RepresentativeName *V1ProviderName `json:"representativeName,omitempty"`
}

// Validate validates this v1 provider
func (m *V1Provider) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRepresentativeName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1Provider) validateAddress(formats strfmt.Registry) error {
	if swag.IsZero(m.Address) { // not required
		return nil
	}

	if m.Address != nil {
		if err := m.Address.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("address")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("address")
			}
			return err
		}
	}

	return nil
}

func (m *V1Provider) validateRepresentativeName(formats strfmt.Registry) error {
	if swag.IsZero(m.RepresentativeName) { // not required
		return nil
	}

	if m.RepresentativeName != nil {
		if err := m.RepresentativeName.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("representativeName")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("representativeName")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 provider based on the context it is used
func (m *V1Provider) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAddress(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRepresentativeName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1Provider) contextValidateAddress(ctx context.Context, formats strfmt.Registry) error {

	if m.Address != nil {
		if err := m.Address.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("address")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("address")
			}
			return err
		}
	}

	return nil
}

func (m *V1Provider) contextValidateRepresentativeName(ctx context.Context, formats strfmt.Registry) error {

	if m.RepresentativeName != nil {
		if err := m.RepresentativeName.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("representativeName")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("representativeName")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1Provider) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Provider) UnmarshalBinary(b []byte) error {
	var res V1Provider
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
