// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1Resource カスタムフィールドマスター
//
// swagger:model v1Resource
type V1Resource struct {

	// カスタムフィールド
	CustomFields map[string]string `json:"customFields,omitempty"`

	// リソースID
	ID string `json:"id,omitempty"`
}

// Validate validates this v1 resource
func (m *V1Resource) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 resource based on context it is used
func (m *V1Resource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1Resource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Resource) UnmarshalBinary(b []byte) error {
	var res V1Resource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
