// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1UsageUnit 使用量単位
//
// swagger:model v1UsageUnit
type V1UsageUnit struct {

	// description
	Description string `json:"description,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// optional Id
	OptionalID string `json:"optionalId,omitempty"`
}

// Validate validates this v1 usage unit
func (m *V1UsageUnit) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 usage unit based on context it is used
func (m *V1UsageUnit) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1UsageUnit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1UsageUnit) UnmarshalBinary(b []byte) error {
	var res V1UsageUnit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
