// Code generated by go-swagger; DO NOT EDIT.

package billing_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewBillingServiceListBillingsByContract2Params creates a new BillingServiceListBillingsByContract2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBillingServiceListBillingsByContract2Params() *BillingServiceListBillingsByContract2Params {
	return &BillingServiceListBillingsByContract2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewBillingServiceListBillingsByContract2ParamsWithTimeout creates a new BillingServiceListBillingsByContract2Params object
// with the ability to set a timeout on a request.
func NewBillingServiceListBillingsByContract2ParamsWithTimeout(timeout time.Duration) *BillingServiceListBillingsByContract2Params {
	return &BillingServiceListBillingsByContract2Params{
		timeout: timeout,
	}
}

// NewBillingServiceListBillingsByContract2ParamsWithContext creates a new BillingServiceListBillingsByContract2Params object
// with the ability to set a context for a request.
func NewBillingServiceListBillingsByContract2ParamsWithContext(ctx context.Context) *BillingServiceListBillingsByContract2Params {
	return &BillingServiceListBillingsByContract2Params{
		Context: ctx,
	}
}

// NewBillingServiceListBillingsByContract2ParamsWithHTTPClient creates a new BillingServiceListBillingsByContract2Params object
// with the ability to set a custom HTTPClient for a request.
func NewBillingServiceListBillingsByContract2ParamsWithHTTPClient(client *http.Client) *BillingServiceListBillingsByContract2Params {
	return &BillingServiceListBillingsByContract2Params{
		HTTPClient: client,
	}
}

/*
BillingServiceListBillingsByContract2Params contains all the parameters to send to the API endpoint

	for the billing service list billings by contract2 operation.

	Typically these are written to a http.Request.
*/
type BillingServiceListBillingsByContract2Params struct {

	/* ID.

	   契約ID
	*/
	ID string

	/* OptionalID.

	   契約管理ID(契約IDの代わりに指定可)
	*/
	OptionalID string

	/* OrderByDirection.

	     - DIRECTION_ASCENDING: 昇順
	- DIRECTION_DESCENDING: 降順
	*/
	OrderByDirection *string

	/* OrderByField.

	     - FIELD_ID: 請求ID
	- FIELD_BILLING_DATE: 請求日
	*/
	OrderByField *string

	/* PageSize.

	   一覧取得する最大数

	   Format: int32
	*/
	PageSize *int32

	/* PageToken.

	   一覧取得に使用するトークン
	*/
	PageToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the billing service list billings by contract2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BillingServiceListBillingsByContract2Params) WithDefaults() *BillingServiceListBillingsByContract2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the billing service list billings by contract2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BillingServiceListBillingsByContract2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) WithTimeout(timeout time.Duration) *BillingServiceListBillingsByContract2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) WithContext(ctx context.Context) *BillingServiceListBillingsByContract2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) WithHTTPClient(client *http.Client) *BillingServiceListBillingsByContract2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) WithID(id string) *BillingServiceListBillingsByContract2Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) SetID(id string) {
	o.ID = id
}

// WithOptionalID adds the optionalID to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) WithOptionalID(optionalID string) *BillingServiceListBillingsByContract2Params {
	o.SetOptionalID(optionalID)
	return o
}

// SetOptionalID adds the optionalId to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) SetOptionalID(optionalID string) {
	o.OptionalID = optionalID
}

// WithOrderByDirection adds the orderByDirection to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) WithOrderByDirection(orderByDirection *string) *BillingServiceListBillingsByContract2Params {
	o.SetOrderByDirection(orderByDirection)
	return o
}

// SetOrderByDirection adds the orderByDirection to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) SetOrderByDirection(orderByDirection *string) {
	o.OrderByDirection = orderByDirection
}

// WithOrderByField adds the orderByField to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) WithOrderByField(orderByField *string) *BillingServiceListBillingsByContract2Params {
	o.SetOrderByField(orderByField)
	return o
}

// SetOrderByField adds the orderByField to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) SetOrderByField(orderByField *string) {
	o.OrderByField = orderByField
}

// WithPageSize adds the pageSize to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) WithPageSize(pageSize *int32) *BillingServiceListBillingsByContract2Params {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) SetPageSize(pageSize *int32) {
	o.PageSize = pageSize
}

// WithPageToken adds the pageToken to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) WithPageToken(pageToken *string) *BillingServiceListBillingsByContract2Params {
	o.SetPageToken(pageToken)
	return o
}

// SetPageToken adds the pageToken to the billing service list billings by contract2 params
func (o *BillingServiceListBillingsByContract2Params) SetPageToken(pageToken *string) {
	o.PageToken = pageToken
}

// WriteToRequest writes these params to a swagger request
func (o *BillingServiceListBillingsByContract2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := qrID
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	// query param optionalId
	qrOptionalID := o.OptionalID
	qOptionalID := qrOptionalID
	if qOptionalID != "" {

		if err := r.SetQueryParam("optionalId", qOptionalID); err != nil {
			return err
		}
	}

	if o.OrderByDirection != nil {

		// query param orderBy.direction
		var qrOrderByDirection string

		if o.OrderByDirection != nil {
			qrOrderByDirection = *o.OrderByDirection
		}
		qOrderByDirection := qrOrderByDirection
		if qOrderByDirection != "" {

			if err := r.SetQueryParam("orderBy.direction", qOrderByDirection); err != nil {
				return err
			}
		}
	}

	if o.OrderByField != nil {

		// query param orderBy.field
		var qrOrderByField string

		if o.OrderByField != nil {
			qrOrderByField = *o.OrderByField
		}
		qOrderByField := qrOrderByField
		if qOrderByField != "" {

			if err := r.SetQueryParam("orderBy.field", qOrderByField); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param pageSize
		var qrPageSize int32

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt32(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("pageSize", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.PageToken != nil {

		// query param pageToken
		var qrPageToken string

		if o.PageToken != nil {
			qrPageToken = *o.PageToken
		}
		qPageToken := qrPageToken
		if qPageToken != "" {

			if err := r.SetQueryParam("pageToken", qPageToken); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
